# 🎨 Data Designer Tutorial: Seeding Synthetic Data Generation with an External Dataset

#### 📚 What you'll learn

In this notebook, we will demonstrate how to seed synthetic data generation in Data Designer with an external dataset.

If this is your first time using Data Designer, we recommend starting with the [first notebook](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/1-the-basics/) in this tutorial series.

### 📦 Import Data Designer

- `data_designer.config` provides access to the configuration API.

- `DataDesigner` is the main interface for data generation.

In [1]:
import data_designer.config as dd
from data_designer.interface import DataDesigner

### ⚙️ Initialize the Data Designer interface

- `DataDesigner` is the main object responsible for managing the data generation process.

- When initialized without arguments, the [default model providers](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) are used.

In [2]:
data_designer = DataDesigner()

### 🎛️ Define model configurations

- Each `ModelConfig` defines a model that can be used during the generation process.

- The "model alias" is used to reference the model in the Data Designer config (as we will see below).

- The "model provider" is the external service that hosts the model (see the [model config](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) docs for more details).

- By default, we use [build.nvidia.com](https://build.nvidia.com/models) as the model provider.

In [3]:
# This name is set in the model provider configuration.
MODEL_PROVIDER = "nvidia"

# The model ID is from build.nvidia.com.
MODEL_ID = "nvidia/nemotron-3-nano-30b-a3b"

# We choose this alias to be descriptive for our use case.
MODEL_ALIAS = "nemotron-nano-v3"

model_configs = [
    dd.ModelConfig(
        alias=MODEL_ALIAS,
        model=MODEL_ID,
        provider=MODEL_PROVIDER,
        inference_parameters=dd.ChatCompletionInferenceParams(
            temperature=1.0,
            top_p=1.0,
            max_tokens=2048,
            extra_body={"chat_template_kwargs": {"enable_thinking": False}},
        ),
    )
]

### 🏗️ Initialize the Data Designer Config Builder

- The Data Designer config defines the dataset schema and generation process.

- The config builder provides an intuitive interface for building this configuration.

- The list of model configs is provided to the builder at initialization.

In [4]:
config_builder = dd.DataDesignerConfigBuilder(model_configs=model_configs)

## 🏥 Prepare a seed dataset

- For this notebook, we'll create a synthetic dataset of patient notes.

- We will _seed_ the generation process with a [symptom-to-diagnosis dataset](https://huggingface.co/datasets/gretelai/symptom_to_diagnosis).

- We already have the dataset downloaded in the [data](../data) directory of this repository.

<br>

> 🌱 **Why use a seed dataset?**
>
> - Seed datasets let you steer the generation process by providing context that is specific to your use case.
>
> - Seed datasets are also an excellent way to inject real-world diversity into your synthetic data.
>
> - During generation, prompt templates can reference any of the seed dataset fields.

In [5]:
# Download sample dataset from Github
import urllib.request

url = "https://raw.githubusercontent.com/NVIDIA/GenerativeAIExamples/refs/heads/main/nemo/NeMo-Data-Designer/data/gretelai_symptom_to_diagnosis.csv"
local_filename, _ = urllib.request.urlretrieve(url, "gretelai_symptom_to_diagnosis.csv")

# Seed datasets are passed as reference objects to the config builder.
seed_source = dd.LocalFileSeedSource(path=local_filename)

config_builder.with_seed_dataset(seed_source)

DataDesignerConfigBuilder(
    seed_dataset: local seed
)

## 🎨 Designing our synthetic patient notes dataset

- The prompt template can reference fields from our seed dataset:
  - `{{ diagnosis }}` - the medical diagnosis from the seed data
  - `{{ patient_summary }}` - the symptom description from the seed data

In [6]:
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="patient_sampler",
        sampler_type=dd.SamplerType.PERSON_FROM_FAKER,
        params=dd.PersonFromFakerSamplerParams(),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="doctor_sampler",
        sampler_type=dd.SamplerType.PERSON_FROM_FAKER,
        params=dd.PersonFromFakerSamplerParams(),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="patient_id",
        sampler_type=dd.SamplerType.UUID,
        params=dd.UUIDSamplerParams(
            prefix="PT-",
            short_form=True,
            uppercase=True,
        ),
    )
)

config_builder.add_column(dd.ExpressionColumnConfig(name="first_name", expr="{{ patient_sampler.first_name }}"))

config_builder.add_column(dd.ExpressionColumnConfig(name="last_name", expr="{{ patient_sampler.last_name }}"))

config_builder.add_column(dd.ExpressionColumnConfig(name="dob", expr="{{ patient_sampler.birth_date }}"))

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="symptom_onset_date",
        sampler_type=dd.SamplerType.DATETIME,
        params=dd.DatetimeSamplerParams(start="2024-01-01", end="2024-12-31"),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="date_of_visit",
        sampler_type=dd.SamplerType.TIMEDELTA,
        params=dd.TimeDeltaSamplerParams(dt_min=1, dt_max=30, reference_column_name="symptom_onset_date"),
    )
)

config_builder.add_column(dd.ExpressionColumnConfig(name="physician", expr="Dr. {{ doctor_sampler.last_name }}"))

config_builder.add_column(
    dd.LLMTextColumnConfig(
        name="physician_notes",
        prompt="""\
You are a primary-care physician who just had an appointment with {{ first_name }} {{ last_name }},
who has been struggling with symptoms from {{ diagnosis }} since {{ symptom_onset_date }}.
The date of today's visit is {{ date_of_visit }}.

{{ patient_summary }}

Write careful notes about your visit with {{ first_name }},
as Dr. {{ doctor_sampler.first_name }} {{ doctor_sampler.last_name }}.

Format the notes as a busy doctor might.
Respond with only the notes, no other text.
""",
        model_alias=MODEL_ALIAS,
    )
)

data_designer.validate(config_builder)

[16:32:50] [INFO] ✅ Validation passed

### 🔁 Iteration is key – preview the dataset!

1. Use the `preview` method to generate a sample of records quickly.

2. Inspect the results for quality and format issues.

3. Adjust column configurations, prompts, or parameters as needed.

4. Re-run the preview until satisfied.

In [7]:
preview = data_designer.preview(config_builder, num_records=2)

[16:32:50] [INFO] 🕵️ Preview generation in progress

[16:32:50] [INFO] ✅ Validation passed

[16:32:50] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:32:50] [INFO] 🩺 Running health checks for models...

[16:32:50] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...

[16:32:50] [INFO]   |-- ✅ Passed!

[16:32:50] [INFO] 🌱 Sampling 2 records from seed dataset

[16:32:50] [INFO]   |-- seed dataset size: 820 records

[16:32:50] [INFO]   |-- sampling strategy: ordered

[16:32:50] [INFO] 🎲 Preparing samplers to generate 2 records across 5 columns

[16:32:50] [INFO] (💾 + 💾) Concatenating 2 datasets

[16:32:50] [INFO] 🧩 Generating column `first_name` from expression

[16:32:50] [INFO] 🧩 Generating column `last_name` from expression

[16:32:50] [INFO] 🧩 Generating column `dob` from expression

[16:32:50] [INFO] 🧩 Generating column `physician` from expression

[16:32:50] [INFO] 📝 llm-text model config for column 'physician_notes'

[16:32:50] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[16:32:50] [INFO]   |-- model alias: 'nemotron-nano-v3'

[16:32:50] [INFO]   |-- model provider: 'nvidia'

[16:32:50] [INFO]   |-- inference parameters:

[16:32:50] [INFO]   |  |-- generation_type=chat-completion

[16:32:50] [INFO]   |  |-- max_parallel_requests=4

[16:32:50] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[16:32:50] [INFO]   |  |-- temperature=1.00

[16:32:50] [INFO]   |  |-- top_p=1.00

[16:32:50] [INFO]   |  |-- max_tokens=2048

[16:32:50] [INFO] ⚡️ Processing llm-text column 'physician_notes' with 4 concurrent workers

[16:32:50] [INFO] ⏱️ llm-text column 'physician_notes' will report progress after each record

[16:32:54] [INFO]   |-- 🌗 llm-text column 'physician_notes' progress: 1/2 (50%) complete, 1 ok, 0 failed, 0.29 rec/s, eta 3.5s

[16:32:54] [INFO]   |-- 🌕 llm-text column 'physician_notes' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.50 rec/s, eta 0.0s

[16:32:55] [INFO] 📊 Model usage summary:

[16:32:55] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:32:55] [INFO]   |-- tokens: input=295, output=1051, total=1346, tps=303

[16:32:55] [INFO]   |-- requests: success=2, failed=0, total=2, rpm=27

[16:32:55] [INFO] 📐 Measuring dataset column statistics:

[16:32:55] [INFO]   |-- 🎲 column: 'patient_sampler'

[16:32:55] [INFO]   |-- 🎲 column: 'doctor_sampler'

[16:32:55] [INFO]   |-- 🎲 column: 'patient_id'

[16:32:55] [INFO]   |-- 🧩 column: 'first_name'

[16:32:55] [INFO]   |-- 🧩 column: 'last_name'

[16:32:55] [INFO]   |-- 🧩 column: 'dob'

[16:32:55] [INFO]   |-- 🎲 column: 'symptom_onset_date'

[16:32:55] [INFO]   |-- 🎲 column: 'date_of_visit'

[16:32:55] [INFO]   |-- 🧩 column: 'physician'

[16:32:55] [INFO]   |-- 📝 column: 'physician_notes'

[16:32:55] [INFO] 🥳 Preview complete!

In [8]:
# Run this cell multiple times to cycle through the 2 preview records.
preview.display_sample_record()

                                                 Seed Columns
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name            ┃ Value                                                                                    ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ diagnosis       │ cervical spondylosis                                                                     │
├─────────────────┼──────────────────────────────────────────────────────────────────────────────────────────┤
│ patient_summary │ I've been having a lot of pain in my neck and back. I've also been having trouble with   │
│                 │ my balance and coordination. I've been coughing a lot and my limbs feel weak.            │
└─────────────────┴──────────────────────────────────────────────────────────────────────────────────────────┘


                                              Generated Columns
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name               ┃ Value                                                                                 ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ patient_sampler    │ {                                                                                     │
│                    │     'uuid': 'e11662ab-ecd0-4785-814e-5720324ae7b4',                                   │
│                    │     'locale': 'en_US',                                                                │
│                    │     'first_name': 'Michelle',                                                         │
│                    │     'last_name': 'Jones',                                                             │
│                    │     'middle_name': None,                                                              │
│                    │     'sex': 'Female',                                                                  │
│                    │     'street_number': '311',                                                           │
│                    │     'street_name': 'James Parkways',                                                  │
│                    │     'city': 'Ericastad',                                                              │
│                    │     'state': 'Kansas',                                                                │
│                    │     'postcode': '45834',                                                              │
│                    │     'age': 30,                                                                        │
│                    │     'birth_date': '1995-11-24',                                                       │
│                    │     'country': "Lao People's Democratic Republic",                                    │
│                    │     'marital_status': 'separated',                                                    │
│                    │     'education_level': 'doctorate',                                                   │
│                    │     'unit': '',                                                                       │
│                    │     'occupation': 'Financial planner',                                                │
│                    │     'phone_number': '763-602-0938x8578',                                              │
│                    │     'bachelors_field': 'education'                                                    │
│                    │ }                                                                                     │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ doctor_sampler     │ {                                                                                     │
│                    │     'uuid': 'bd258b7f-b9e1-4137-bae7-0d80ac0bef61',                                   │
│                    │     'locale': 'en_US',                                                                │
│                    │     'first_name': 'Derek',                                                            │
│                    │     'last_name': 'Wolfe',                                                             │
│                    │     'middle_name': None,                                                              │
│                    │     'sex': 'Male',                                                                    │
│                    │     'street_number': '4104',                                                          │
│                    │     'street_name': 'Elizabeth Fall',                                                  │
│                    │     'city': 'Johnburgh',                                                              │
│                    │     'state': 'Hawaii',                                                                │
│                    │     'postcode': '18887',                                                              │
│                    │     'age': 79,                                                                        │
│                    │     'birth_date': '1947-02-20',                                                       │
│                    │     'country': 'Western Sahara',                                                      │
│                    │     'marital_status': 'never_married',                                                │
│                    │     'education_level': 'some_college',                                                │
│                    │     'unit': '',                                                                       │
│                    │     'occupation': 'Town planner',                                                     │
│                    │     'phone_number': '(429)965-5041x055',                                              │
│                    │     'bachelors_field': 'no_degree'                                                    │
│                    │ }                                                                                     │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ patient_id         │ PT-9A523559                                                                           │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ symptom_onset_date │ 2024-06-05                                                                            │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ date_of_visit      │ 2024-06-13                                                                            │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ physician_notes    │ **APPT 06/13/2024 - Micical JONES**                                                   │
│                    │ **DOB:** 01/15/1982 **MRN:** 55219                                                    │
│                    │ **C/O:** Neck/back pain, chronic, 2024-06-05 onset, worsening. "Feels like a vice in  │
│                    │ my neck."                                                                             │
│                    │ **HPI:** 9 days of constant axial neck pain, radiating to occiput. Pain 7/10, worst   │
│                    │ with movement; 3/10 at rest. No radiculopathy (no arm numbness/weakness). New:        │
│                    │ worsening balance, "stumbling," clumsiness. Pre-existing cervical spondylosis         │
│                    │ (diagnosed 2020). No recent trauma.                                                   │
│                    │ **ROS:**                                                                              │
│                    │ - **Neuro:** New imbalance, frequent falls (3x this week), mild hand weakness (drops  │
│                    │ objects). No bowel/bladder issues.                                                    │
│                    │ - **Resp:** Productive cough, 10 days, worsening.                                     │
│                    │ - **Neuro:** Chronic pain (history); acute exacerbation.                              │
│                    │ **PMH:** Cervical spondylosis (2020), mild asthma. **Med:** OTC acetaminophen,        │
│                    │ albuterol PRN.                                                                        │
│                    │ **Exams:**                                                                            │
│                    │ - **Neck:** Limited flexion/extension (pain at 45°). No tenderness.                   │
│                    │ - **Neuro:** Positive Romberg (unsteady on ROM), mild hand weakness (drops pen). No   │
│                    │ hyperreflexia.                                                                        │
│                    │ - **Resp:** Crackles bilateral bases.                                                 │
│                    │ **Dx:**                                                                               │
│                    │ - Cervical spondylosis with new autonomic/neuro decline (balance, weakness).          │
│                    │ - Acute bronchitis (cough).                                                           │
│                    │ **Plan:**                                                                             │
│                    │ - **Tx:** Cervical traction referral (PT), OTC NSAID (ibuprofen).                     │
│                    │ - **Follow-up:** Neuro eval (next week).                                              │
│                    │ - **Counsel:** Avoid neck hyperextension. Monitor for falls.                          │
│                    │ - **Note:** "Cough may be secondary to postnasal drip; consider ENT if persists >2    │
│                    │ wks."                                                                                 │
│                    │ **Signature:** D. Wolfe, MD                                                           │
│                    │ **Priority:** Follow-up neuro referral *urgent*.                                      │
│                    │ **Type:** Office visit (CPT 99213)                                                    │
│                    │ **Status:** Active                                                                    │
│                    │ **Provider:** Dr. Derek Wolfe, MD                                                     │
│                    │ **Date:** 06/13/2024 09:45 AM                                                         │
│                    │ **Location:** Primary Care Clinic, Room 3B                                            │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ first_name         │ Michelle                                                                              │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ last_name          │ Jones                                                                                 │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ dob                │ 1995-11-24                                                                            │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ physician          │ Dr. Wolfe                                                                             │
└────────────────────┴───────────────────────────────────────────────────────────────────────────────────────┘

In [9]:
# The preview dataset is available as a pandas DataFrame.
preview.dataset

,diagnosis,patient_summary,patient_sampler,doctor_sampler,patient_id,symptom_onset_date,date_of_visit,first_name,last_name,dob,physician,physician_notes
0,cervical spondylosis,I've been having a lot of pain in my neck and ...,{'uuid': 'e11662ab-ecd0-4785-814e-5720324ae7b4...,{'uuid': 'bd258b7f-b9e1-4137-bae7-0d80ac0bef61...,PT-9A523559,2024-06-05,2024-06-13,Michelle,Jones,1995-11-24,Dr. Wolfe,**APPT 06/13/2024 - Micical JONES** \n**DOB:*...
1,impetigo,I have a rash on my face that is getting worse...,{'uuid': '117e8b33-2250-4352-bf22-00100d8c7b17...,{'uuid': '4f225feb-bcef-4198-bc5d-811374c8e03d...,PT-70FE596E,2024-04-10,2024-04-17,Ashlee,Gordon,1997-02-28,Dr. Mcdaniel,4/17/2024 - 14:32 \nPt: Ashlee Gordon (DOB: 0...

### 📊 Analyze the generated data

- Data Designer automatically generates a basic statistical analysis of the generated data.

- This analysis is available via the `analysis` property of generation result objects.

In [10]:
# Print the analysis as a table.
preview.analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2                               │ 10                              │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                   ┃       data type ┃             number unique values ┃               sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ patient_sampler               │            dict │                       2 (100.0%) │          person_from_faker │
├───────────────────────────────┼─────────────────┼──────────────────────────────────┼────────────────────────────┤
│ doctor_sampler                │            dict │                       2 (100.0%) │          person_from_faker │
├───────────────────────────────┼─────────────────┼──────────────────────────────────┼────────────────────────────┤
│ patient_id                    │          string │                       2 (100.0%) │                       uuid │
├───────────────────────────────┼─────────────────┼──────────────────────────────────┼────────────────────────────┤
│ symptom_onset_date            │          string │                       2 (100.0%) │                   datetime │
├───────────────────────────────┼─────────────────┼──────────────────────────────────┼────────────────────────────┤
│ date_of_visit                 │          string │                       2 (100.0%) │                  timedelta │
└───────────────────────────────┴─────────────────┴──────────────────────────────────┴────────────────────────────┘


                                                📝 LLM-Text Columns
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                       ┃               ┃                            ┃     prompt tokens ┃      completion tokens ┃
┃ column name           ┃     data type ┃       number unique values ┃        per record ┃             per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ physician_notes       │        string │                 2 (100.0%) │     124.0 +/- 2.0 │         455.5 +/- 74.2 │
└───────────────────────┴───────────────┴────────────────────────────┴───────────────────┴────────────────────────┘


                                               🧩 Expression Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                    ┃                 data type ┃                               number unique values ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ first_name                     │                    string │                                         2 (100.0%) │
├────────────────────────────────┼───────────────────────────┼────────────────────────────────────────────────────┤
│ last_name                      │                    string │                                         2 (100.0%) │
├────────────────────────────────┼───────────────────────────┼────────────────────────────────────────────────────┤
│ dob                            │                    string │                                         2 (100.0%) │
├────────────────────────────────┼───────────────────────────┼────────────────────────────────────────────────────┤
│ physician                      │                    string │                                         2 (100.0%) │
└────────────────────────────────┴───────────────────────────┴────────────────────────────────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

### 🆙 Scale up!

- Happy with your preview data?

- Use the `create` method to submit larger Data Designer generation jobs.

In [11]:
results = data_designer.create(config_builder, num_records=10, dataset_name="tutorial-3")

[16:32:55] [INFO] 🎨 Creating Data Designer dataset

[16:32:55] [INFO] ✅ Validation passed

[16:32:55] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:32:55] [INFO] 🩺 Running health checks for models...

[16:32:55] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...

[16:32:55] [INFO]   |-- ✅ Passed!

[16:32:55] [INFO] ⏳ Processing batch 1 of 1

[16:32:55] [INFO] 🌱 Sampling 10 records from seed dataset

[16:32:55] [INFO]   |-- seed dataset size: 820 records

[16:32:55] [INFO]   |-- sampling strategy: ordered

[16:32:55] [INFO] 🎲 Preparing samplers to generate 10 records across 5 columns

[16:32:55] [INFO] (💾 + 💾) Concatenating 2 datasets

[16:32:55] [INFO] 🧩 Generating column `first_name` from expression

[16:32:55] [INFO] 🧩 Generating column `last_name` from expression

[16:32:55] [INFO] 🧩 Generating column `dob` from expression

[16:32:55] [INFO] 🧩 Generating column `physician` from expression

[16:32:55] [INFO] 📝 llm-text model config for column 'physician_notes'

[16:32:55] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[16:32:55] [INFO]   |-- model alias: 'nemotron-nano-v3'

[16:32:55] [INFO]   |-- model provider: 'nvidia'

[16:32:55] [INFO]   |-- inference parameters:

[16:32:55] [INFO]   |  |-- generation_type=chat-completion

[16:32:55] [INFO]   |  |-- max_parallel_requests=4

[16:32:55] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[16:32:55] [INFO]   |  |-- temperature=1.00

[16:32:55] [INFO]   |  |-- top_p=1.00

[16:32:55] [INFO]   |  |-- max_tokens=2048

[16:32:55] [INFO] ⚡️ Processing llm-text column 'physician_notes' with 4 concurrent workers

[16:32:55] [INFO] ⏱️ llm-text column 'physician_notes' will report progress after each record

[16:32:59] [INFO]   |-- 🐱 llm-text column 'physician_notes' progress: 1/10 (10%) complete, 1 ok, 0 failed, 0.28 rec/s, eta 32.5s

[16:33:01] [INFO]   |-- 🐱 llm-text column 'physician_notes' progress: 2/10 (20%) complete, 2 ok, 0 failed, 0.35 rec/s, eta 22.8s

[16:33:04] [INFO]   |-- 😺 llm-text column 'physician_notes' progress: 3/10 (30%) complete, 3 ok, 0 failed, 0.33 rec/s, eta 21.2s

[16:33:09] [INFO]   |-- 😺 llm-text column 'physician_notes' progress: 4/10 (40%) complete, 4 ok, 0 failed, 0.29 rec/s, eta 20.4s

[16:33:10] [INFO]   |-- 😸 llm-text column 'physician_notes' progress: 5/10 (50%) complete, 5 ok, 0 failed, 0.35 rec/s, eta 14.2s

[16:33:11] [INFO]   |-- 😸 llm-text column 'physician_notes' progress: 6/10 (60%) complete, 6 ok, 0 failed, 0.37 rec/s, eta 10.7s

[16:33:12] [INFO]   |-- 😸 llm-text column 'physician_notes' progress: 7/10 (70%) complete, 7 ok, 0 failed, 0.43 rec/s, eta 6.9s

[16:33:12] [INFO]   |-- 😼 llm-text column 'physician_notes' progress: 8/10 (80%) complete, 8 ok, 0 failed, 0.49 rec/s, eta 4.0s

[16:33:18] [INFO]   |-- 😼 llm-text column 'physician_notes' progress: 9/10 (90%) complete, 9 ok, 0 failed, 0.40 rec/s, eta 2.5s

[16:33:19] [INFO]   |-- 🦁 llm-text column 'physician_notes' progress: 10/10 (100%) complete, 10 ok, 0 failed, 0.42 rec/s, eta 0.0s

[16:33:20] [INFO] 📊 Model usage summary:

[16:33:20] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:33:20] [INFO]   |-- tokens: input=1440, output=10251, total=11691, tps=477

[16:33:20] [INFO]   |-- requests: success=10, failed=0, total=10, rpm=24

[16:33:20] [INFO] 📐 Measuring dataset column statistics:

[16:33:20] [INFO]   |-- 🎲 column: 'patient_sampler'

[16:33:20] [INFO]   |-- 🎲 column: 'doctor_sampler'

[16:33:20] [INFO]   |-- 🎲 column: 'patient_id'

[16:33:20] [INFO]   |-- 🧩 column: 'first_name'

[16:33:20] [INFO]   |-- 🧩 column: 'last_name'

[16:33:20] [INFO]   |-- 🧩 column: 'dob'

[16:33:20] [INFO]   |-- 🎲 column: 'symptom_onset_date'

[16:33:20] [INFO]   |-- 🎲 column: 'date_of_visit'

[16:33:20] [INFO]   |-- 🧩 column: 'physician'

[16:33:20] [INFO]   |-- 📝 column: 'physician_notes'

In [12]:
# Load the generated dataset as a pandas DataFrame.
dataset = results.load_dataset()

dataset.head()

,diagnosis,patient_summary,patient_sampler,doctor_sampler,patient_id,symptom_onset_date,date_of_visit,first_name,last_name,dob,physician,physician_notes
0,cervical spondylosis,I've been having a lot of pain in my neck and ...,"{'age': 49, 'bachelors_field': 'stem', 'birth_...","{'age': 69, 'bachelors_field': 'no_degree', 'b...",PT-799371FC,2024-04-01,2024-04-16,Stephen,Warner,1976-09-22,Dr. Forbes,**Visit Note – 2024-04-16** **Patient:** Ste...
1,impetigo,I have a rash on my face that is getting worse...,"{'age': 45, 'bachelors_field': 'no_degree', 'b...","{'age': 85, 'bachelors_field': 'arts_humanitie...",PT-C40BC90C,2024-06-12,2024-06-29,Peter,Robles,1980-10-31,Dr. Taylor,Date: 2024-06-29 Patient: Peter Robles Vitals:...
2,urinary tract infection,I have been urinating blood. I sometimes feel ...,"{'age': 31, 'bachelors_field': 'no_degree', 'b...","{'age': 19, 'bachelors_field': 'stem', 'birth_...",PT-7A073D62,2024-12-10,2025-01-06,Robert,Gomez,1994-10-18,Dr. Smith,**Patient:** Robert Gomez **DOB:** 04/12/197...
3,arthritis,I have been having trouble with my muscles and...,"{'age': 33, 'bachelors_field': 'no_degree', 'b...","{'age': 84, 'bachelors_field': 'no_degree', 'b...",PT-11F01037,2024-01-05,2024-02-02,Tracie,Campbell,1993-01-20,Dr. Ingram,**Patient:** Tracie Campbell **DOB:** 04/12/...
4,dengue,I have been feeling really sick. My body hurts...,"{'age': 25, 'bachelors_field': 'no_degree', 'b...","{'age': 73, 'bachelors_field': 'stem', 'birth_...",PT-4E4F733E,2024-10-11,2024-11-04,Laura,Walters,2000-04-30,Dr. King,**SOAP Note - Dr. Danielle King** **Date:** ...

In [13]:
# Load the analysis results into memory.
analysis = results.load_analysis()

analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 10                              │ 10                              │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                   ┃       data type ┃             number unique values ┃               sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ patient_sampler               │            dict │                      10 (100.0%) │          person_from_faker │
├───────────────────────────────┼─────────────────┼──────────────────────────────────┼────────────────────────────┤
│ doctor_sampler                │            dict │                      10 (100.0%) │          person_from_faker │
├───────────────────────────────┼─────────────────┼──────────────────────────────────┼────────────────────────────┤
│ patient_id                    │          string │                      10 (100.0%) │                       uuid │
├───────────────────────────────┼─────────────────┼──────────────────────────────────┼────────────────────────────┤
│ symptom_onset_date            │          string │                        9 (90.0%) │                   datetime │
├───────────────────────────────┼─────────────────┼──────────────────────────────────┼────────────────────────────┤
│ date_of_visit                 │          string │                      10 (100.0%) │                  timedelta │
└───────────────────────────────┴─────────────────┴──────────────────────────────────┴────────────────────────────┘


                                                📝 LLM-Text Columns
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                       ┃               ┃                            ┃     prompt tokens ┃      completion tokens ┃
┃ column name           ┃     data type ┃       number unique values ┃        per record ┃             per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ physician_notes       │        string │                10 (100.0%) │     119.0 +/- 5.4 │        968.5 +/- 427.0 │
└───────────────────────┴───────────────┴────────────────────────────┴───────────────────┴────────────────────────┘


                                               🧩 Expression Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                    ┃                 data type ┃                               number unique values ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ first_name                     │                    string │                                          9 (90.0%) │
├────────────────────────────────┼───────────────────────────┼────────────────────────────────────────────────────┤
│ last_name                      │                    string │                                        10 (100.0%) │
├────────────────────────────────┼───────────────────────────┼────────────────────────────────────────────────────┤
│ dob                            │                    string │                                        10 (100.0%) │
├────────────────────────────────┼───────────────────────────┼────────────────────────────────────────────────────┤
│ physician                      │                    string │                                        10 (100.0%) │
└────────────────────────────────┴───────────────────────────┴────────────────────────────────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

## ⏭️ Next Steps

Check out the following notebook to learn more about:

- [Providing images as context](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/4-providing-images-as-context/)

- [Generating images](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/5-generating-images/)