# 🎨 Data Designer Tutorial: The Basics

#### 📚 What you'll learn

This notebook demonstrates the basics of Data Designer by generating a simple product review dataset.

### 📦 Import Data Designer

- `data_designer.config` provides access to the configuration API.

- `DataDesigner` is the main interface for data generation.

In [1]:
import data_designer.config as dd
from data_designer.interface import DataDesigner

### ⚙️ Initialize the Data Designer interface

- `DataDesigner` is the main object responsible for managing the data generation process.

- When initialized without arguments, the [default model providers](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) are used.

In [2]:
data_designer = DataDesigner()

### 🎛️ Define model configurations

- Each `ModelConfig` defines a model that can be used during the generation process.

- The "model alias" is used to reference the model in the Data Designer config (as we will see below).

- The "model provider" is the external service that hosts the model (see the [model config](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) docs for more details).

- By default, we use [build.nvidia.com](https://build.nvidia.com/models) as the model provider.

In [3]:
# This name is set in the model provider configuration.
MODEL_PROVIDER = "nvidia"

# The model ID is from build.nvidia.com.
MODEL_ID = "nvidia/nemotron-3-nano-30b-a3b"

# We choose this alias to be descriptive for our use case.
MODEL_ALIAS = "nemotron-nano-v3"

model_configs = [
    dd.ModelConfig(
        alias=MODEL_ALIAS,
        model=MODEL_ID,
        provider=MODEL_PROVIDER,
        inference_parameters=dd.ChatCompletionInferenceParams(
            temperature=1.0,
            top_p=1.0,
            max_tokens=2048,
            extra_body={"chat_template_kwargs": {"enable_thinking": False}},
        ),
    )
]

### 🏗️ Initialize the Data Designer Config Builder

- The Data Designer config defines the dataset schema and generation process.

- The config builder provides an intuitive interface for building this configuration.

- The list of model configs is provided to the builder at initialization.

In [4]:
config_builder = dd.DataDesignerConfigBuilder(model_configs=model_configs)

## 🎲 Getting started with sampler columns

- Sampler columns offer non-LLM based generation of synthetic data.

- They are particularly useful for **steering the diversity** of the generated data, as we demonstrate below.

<br>

You can view available samplers using the config builder's `info` property:

In [5]:
config_builder.info.display("samplers")

─────────────────────────────────────────── NeMo Data Designer Samplers ───────────────────────────────────────────

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ Type               ┃ Parameter                ┃ Data Type                         ┃ Required ┃ Constraints      ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ bernoulli          │ p                        │ number                            │    ✓     │ >= 0.0, <= 1.0   │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ bernoulli_mixture  │ p                        │ number                            │    ✓     │ >= 0.0, <= 1.0   │
│                    │ dist_name                │ string                            │    ✓     │                  │
│                    │ dist_params              │ dict                              │    ✓     │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ binomial           │ n                        │ integer                           │    ✓     │                  │
│                    │ p                        │ number                            │    ✓     │ >= 0.0, <= 1.0   │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ category           │ values                   │ string[] | integer[] | number[]   │    ✓     │ len > 1          │
│                    │ weights                  │ number[] | null                   │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ datetime           │ start                    │ string                            │    ✓     │                  │
│                    │ end                      │ string                            │    ✓     │                  │
│                    │ unit                     │ string                            │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ gaussian           │ mean                     │ number                            │    ✓     │                  │
│                    │ stddev                   │ number                            │    ✓     │                  │
│                    │ decimal_places           │ integer | null                    │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ person             │ locale                   │ string                            │          │                  │
│                    │ sex                      │ string | null                     │          │                  │
│                    │ city                     │ string | string[] | null          │          │                  │
│                    │ age_range                │ integer[]                         │          │ len > 2, len < 2 │
│                    │ select_field_values      │ object | null                     │          │                  │
│                    │ with_synthetic_personas  │ boolean                           │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ person_from_faker  │ locale                   │ string                            │          │                  │
│                    │ sex                      │ string | null                     │          │                  │
│                    │ city                     │ string | string[] | null          │          │                  │
│                    │ age_range                │ integer[]                         │          │ len > 2, len < 2 │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ poisson            │ mean                     │ number                            │    ✓     │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ scipy              │ dist_name                │ string                            │    ✓     │                  │
│                    │ dist_params              │ dict                              │    ✓     │                  │
│                    │ decimal_places           │ integer | null                    │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ subcategory        │ category                 │ string                            │    ✓     │                  │
│                    │ values                   │ dict                              │    ✓     │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ timedelta          │ dt_min                   │ integer                           │    ✓     │ >= 0             │
│                    │ dt_max                   │ integer                           │    ✓     │ > 0              │
│                    │ reference_column_name    │ string                            │    ✓     │                  │
│                    │ unit                     │ string                            │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ uniform            │ low                      │ number                            │    ✓     │                  │
│                    │ high                     │ number                            │    ✓     │                  │
│                    │ decimal_places           │ integer | null                    │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
├────────────────────┼──────────────────────────┼───────────────────────────────────┼──────────┼──────────────────┤
│ uuid               │ prefix                   │ string | null                     │          │                  │
│                    │ short_form               │ boolean                           │          │                  │
│                    │ uppercase                │ boolean                           │          │                  │
│                    │ sampler_type             │ string                            │          │                  │
└────────────────────┴──────────────────────────┴───────────────────────────────────┴──────────┴──────────────────┘

Let's start designing our product review dataset by adding product category and subcategory columns.

In [6]:
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="product_category",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(
            values=[
                "Electronics",
                "Clothing",
                "Home & Kitchen",
                "Books",
                "Home Office",
            ],
        ),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="product_subcategory",
        sampler_type=dd.SamplerType.SUBCATEGORY,
        params=dd.SubcategorySamplerParams(
            category="product_category",
            values={
                "Electronics": [
                    "Smartphones",
                    "Laptops",
                    "Headphones",
                    "Cameras",
                    "Accessories",
                ],
                "Clothing": [
                    "Men's Clothing",
                    "Women's Clothing",
                    "Winter Coats",
                    "Activewear",
                    "Accessories",
                ],
                "Home & Kitchen": [
                    "Appliances",
                    "Cookware",
                    "Furniture",
                    "Decor",
                    "Organization",
                ],
                "Books": [
                    "Fiction",
                    "Non-Fiction",
                    "Self-Help",
                    "Textbooks",
                    "Classics",
                ],
                "Home Office": [
                    "Desks",
                    "Chairs",
                    "Storage",
                    "Office Supplies",
                    "Lighting",
                ],
            },
        ),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="target_age_range",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(values=["18-25", "25-35", "35-50", "50-65", "65+"]),
    )
)

# Optionally validate that the columns are configured correctly.
data_designer.validate(config_builder)

[16:32:08] [INFO] ✅ Validation passed

Next, let's add samplers to generate data related to the customer and their review.

In [7]:
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="customer",
        sampler_type=dd.SamplerType.PERSON_FROM_FAKER,
        params=dd.PersonFromFakerSamplerParams(age_range=[18, 70], locale="en_US"),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="number_of_stars",
        sampler_type=dd.SamplerType.UNIFORM,
        params=dd.UniformSamplerParams(low=1, high=5),
        convert_to="int",  # Convert the sampled float to an integer.
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="review_style",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(
            values=["rambling", "brief", "detailed", "structured with bullet points"],
            weights=[1, 2, 2, 1],
        ),
    )
)

data_designer.validate(config_builder)

[16:32:08] [INFO] ✅ Validation passed

## 🦜 LLM-generated columns

- The real power of Data Designer comes from leveraging LLMs to generate text, code, and structured data.

- When prompting the LLM, we can use Jinja templating to reference other columns in the dataset.

- As we see below, nested json fields can be accessed using dot notation.

In [8]:
config_builder.add_column(
    dd.LLMTextColumnConfig(
        name="product_name",
        prompt=(
            "You are a helpful assistant that generates product names. DO NOT add quotes around the product name.\n\n"
            "Come up with a creative product name for a product in the '{{ product_category }}' category, focusing "
            "on products related to '{{ product_subcategory }}'. The target age range of the ideal customer is "
            "{{ target_age_range }} years old. Respond with only the product name, no other text."
        ),
        model_alias=MODEL_ALIAS,
    )
)

config_builder.add_column(
    dd.LLMTextColumnConfig(
        name="customer_review",
        prompt=(
            "You are a customer named {{ customer.first_name }} from {{ customer.city }}, {{ customer.state }}. "
            "You are {{ customer.age }} years old and recently purchased a product called {{ product_name }}. "
            "Write a review of this product, which you gave a rating of {{ number_of_stars }} stars. "
            "The style of the review should be '{{ review_style }}'. "
            "Respond with only the review, no other text."
        ),
        model_alias=MODEL_ALIAS,
    )
)

data_designer.validate(config_builder)

[16:32:08] [INFO] ✅ Validation passed

### 🔁 Iteration is key – preview the dataset!

1. Use the `preview` method to generate a sample of records quickly.

2. Inspect the results for quality and format issues.

3. Adjust column configurations, prompts, or parameters as needed.

4. Re-run the preview until satisfied.

In [9]:
preview = data_designer.preview(config_builder, num_records=2)

[16:32:08] [INFO] 🔭 Preview generation in progress

[16:32:08] [INFO] ✅ Validation passed

[16:32:08] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:32:08] [INFO] 🩺 Running health checks for models...

[16:32:08] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...

[16:32:09] [INFO]   |-- ✅ Passed!

[16:32:09] [INFO] 🎲 Preparing samplers to generate 2 records across 6 columns

[16:32:11] [INFO] 📝 llm-text model config for column 'product_name'

[16:32:11] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[16:32:11] [INFO]   |-- model alias: 'nemotron-nano-v3'

[16:32:11] [INFO]   |-- model provider: 'nvidia'

[16:32:11] [INFO]   |-- inference parameters:

[16:32:11] [INFO]   |  |-- generation_type=chat-completion

[16:32:11] [INFO]   |  |-- max_parallel_requests=4

[16:32:11] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[16:32:11] [INFO]   |  |-- temperature=1.00

[16:32:11] [INFO]   |  |-- top_p=1.00

[16:32:11] [INFO]   |  |-- max_tokens=2048

[16:32:11] [INFO] ⚡️ Processing llm-text column 'product_name' with 4 concurrent workers

[16:32:11] [INFO] ⏱️ llm-text column 'product_name' will report progress after each record

[16:32:11] [INFO]   |-- 🚗 llm-text column 'product_name' progress: 1/2 (50%) complete, 1 ok, 0 failed, 2.83 rec/s, eta 0.4s

[16:32:11] [INFO]   |-- 🚀 llm-text column 'product_name' progress: 2/2 (100%) complete, 2 ok, 0 failed, 5.31 rec/s, eta 0.0s

[16:32:11] [INFO] 📝 llm-text model config for column 'customer_review'

[16:32:11] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[16:32:11] [INFO]   |-- model alias: 'nemotron-nano-v3'

[16:32:11] [INFO]   |-- model provider: 'nvidia'

[16:32:11] [INFO]   |-- inference parameters:

[16:32:11] [INFO]   |  |-- generation_type=chat-completion

[16:32:11] [INFO]   |  |-- max_parallel_requests=4

[16:32:11] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[16:32:11] [INFO]   |  |-- temperature=1.00

[16:32:11] [INFO]   |  |-- top_p=1.00

[16:32:11] [INFO]   |  |-- max_tokens=2048

[16:32:11] [INFO] ⚡️ Processing llm-text column 'customer_review' with 4 concurrent workers

[16:32:11] [INFO] ⏱️ llm-text column 'customer_review' will report progress after each record

[16:32:14] [INFO]   |-- 😐 llm-text column 'customer_review' progress: 1/2 (50%) complete, 1 ok, 0 failed, 0.39 rec/s, eta 2.5s

[16:32:17] [INFO]   |-- 🤩 llm-text column 'customer_review' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.36 rec/s, eta 0.0s

[16:32:17] [INFO] 📊 Model usage summary:

[16:32:17] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:32:17] [INFO]   |-- tokens: input=362, output=1159, total=1521, tps=188

[16:32:17] [INFO]   |-- requests: success=4, failed=0, total=4, rpm=29

[16:32:17] [INFO] 📐 Measuring dataset column statistics:

[16:32:17] [INFO]   |-- 🎲 column: 'product_category'

[16:32:17] [INFO]   |-- 🎲 column: 'product_subcategory'

[16:32:17] [INFO]   |-- 🎲 column: 'target_age_range'

[16:32:17] [INFO]   |-- 🎲 column: 'customer'

[16:32:17] [INFO]   |-- 🎲 column: 'number_of_stars'

[16:32:17] [INFO]   |-- 🎲 column: 'review_style'

[16:32:17] [INFO]   |-- 📝 column: 'product_name'

[16:32:18] [INFO]   |-- 📝 column: 'customer_review'

[16:32:18] [INFO] 🍾 Preview complete!

In [10]:
# Run this cell multiple times to cycle through the 2 preview records.
preview.display_sample_record()

                                              Generated Columns
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                ┃ Value                                                                                ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category    │ Home Office                                                                          │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ product_subcategory │ Office Supplies                                                                      │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ target_age_range    │ 18-25                                                                                │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer            │ {                                                                                    │
│                     │     'uuid': 'ec9d7022-089a-4b2f-b82c-0d87f0ea2e62',                                  │
│                     │     'locale': 'en_US',                                                               │
│                     │     'first_name': 'Denise',                                                          │
│                     │     'last_name': 'Stout',                                                            │
│                     │     'middle_name': None,                                                             │
│                     │     'sex': 'Female',                                                                 │
│                     │     'street_number': '77469',                                                        │
│                     │     'street_name': 'Dawn Square',                                                    │
│                     │     'city': 'East Stephen',                                                          │
│                     │     'state': 'Nevada',                                                               │
│                     │     'postcode': '33904',                                                             │
│                     │     'age': 19,                                                                       │
│                     │     'birth_date': '2006-07-09',                                                      │
│                     │     'country': 'British Indian Ocean Territory (Chagos Archipelago)',                │
│                     │     'marital_status': 'never_married',                                               │
│                     │     'education_level': 'secondary_education',                                        │
│                     │     'unit': '',                                                                      │
│                     │     'occupation': 'Runner, broadcasting/film/video',                                 │
│                     │     'phone_number': '520.454.5404x378',                                              │
│                     │     'bachelors_field': 'no_degree'                                                   │
│                     │ }                                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ number_of_stars     │ 3                                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ review_style        │ detailed                                                                             │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ product_name        │ ErgoCharge Smart Desk Mat Harmony                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer_review     │ **Denise from East Stephen, Nevada – 19 years old – 3‑Star Detailed Review**         │
│                     │                                                                                      │
│                     │ I bought the ErgoCharge Smart Desk Mat Harmony a month ago, excited to try out a     │
│                     │ “high‑tech” anti‑fatigue mat that also claims to charge my devices. Overall, it’s    │
│                     │ decent but falls short of my expectations in a few key areas.                        │
│                     │                                                                                      │
│                     │ **First Impressions & Build Quality**                                                │
│                     │ The mat arrived in a sleek, matte black box with a thin instruction manual. When I   │
│                     │ unrolled it, the surface felt surprisingly plush—soft enough to cushion my wrists    │
│                     │ but firm enough to keep my laptop stable. The silicone edge trim looks durable, and  │
│                     │ the embedded LED strip gave a subtle glow that I liked. However, the stitching along │
│                     │ the border is a bit loose in places; after a few days of use, I noticed tiny fraying │
│                     │ threads near the corners.                                                            │
│                     │                                                                                      │
│                     │ **Ergonomic Design**                                                                 │
│                     │ The mat is marketed as an “ErgoCharge” solution, promising wrist support and posture │
│                     │ improvement. My wrist rests comfortably on the gel‑infused foam, and I haven’t felt  │
│                     │ the usual soreness after long coding sessions. The mat’s slight incline (about 5°)   │
│                     │ encourages a more neutral wrist angle, which I’ve read about in ergonomics guides.   │
│                     │ Still, the incline is subtle—if you’re looking for a pronounced tilt, you’ll need to │
│                     │ adjust your chair or desk separately.                                                │
│                     │                                                                                      │
│                     │ **Smart Features & Charging**                                                        │
│                     │ The biggest selling point for me was the “Smart” aspect: wireless Qi charging and    │
│                     │ integrated cable management. The charging pad works well for my phone and a small    │
│                     │ smartwatch, but it only sustained a 5W output—so my phone charges slowly, and it     │
│                     │ refuses to charge anything larger than 6 mm thickness. The mat features a hidden     │
│                     │ channel to route USB-C or power cords, which is neat, but the channel is shallow; my │
│                     │ longer cords keep slipping out when I move the mat.                                  │
│                     │                                                                                      │
│                     │ **Sensor & Feedback System**                                                         │
│                     │ There’s a tiny embedded sensor that supposedly monitors desk usage and provides      │
│                     │ vibration alerts when you’ve been sitting too long. In practice, the sensor is       │
│                     │ finicky: it sometimes registers “movement” when I just shift my weight, and other    │
│                     │ times it stays silent for hours despite extended periods of stillness. The companion │
│                     │ app on my phone is minimalistic—only shows a basic usage timer and battery level for │
│                     │ the mat’s internal LED—but it crashes intermittently on my Android 13 device.        │
│                     │                                                                                      │
│                     │ **Durability & Maintenance**                                                         │
│                     │ After a month of daily use, the surface shows no staining, and the anti‑slip rubber  │
│                     │ base remains firmly attached to my desk. I’ve spilled a little coffee, wiped it off  │
│                     │ with a damp cloth, and the mat looked fine, but I’m concerned about long‑term wear   │
│                     │ on the foam edge. The mat’s claim of “lifetime warranty” sounds appealing, yet the   │
│                     │ fine print requires a registration within 14 days and a copy of the purchase         │
│                     │ receipt—something I missed, so I’m technically out of warranty.                      │
│                     │                                                                                      │
│                     │ **Value for Money**                                                                  │
│                     │ Priced at $79.99, the mat sits in the mid‑range market for ergonomic accessories.    │
│                     │ The charging capability, decent wrist support, and aesthetic LED lighting do add     │
│                     │ some value, but the inconsistent sensor, weak wireless charging speed, and           │
│                     │ occasional stitching issues make it hard to justify the full price. I’d consider     │
│                     │ paying $50‑$55 for a product with these features, but the current price feels a bit  │
│                     │ inflated for what the mat actually delivers.                                         │
│                     │                                                                                      │
│                     │ **Final Thoughts**                                                                   │
│                     │ If you’re looking for a simple wrist‑support mat with a subtle aesthetic boost, the  │
│                     │ ErgoCharge Smart Desk Mat Harmony works okay. However, expect limited wireless       │
│                     │ charging power, an unreliable usage sensor, and a build quality that doesn’t feel    │
│                     │ premium. I’m giving it 3 stars because it meets some expectations but falls short in │
│                     │ several key areas that matter for daily office use. I’ll probably keep it for now as │
│                     │ a cost‑effective option, but I’d look for a more robust alternative before buying    │
│                     │ another.                                                                             │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┘

In [11]:
# The preview dataset is available as a pandas DataFrame.
preview.dataset

,product_category,product_subcategory,target_age_range,customer,number_of_stars,review_style,product_name,customer_review
0,Home Office,Office Supplies,18-25,{'uuid': 'ec9d7022-089a-4b2f-b82c-0d87f0ea2e62...,3,detailed,ErgoCharge Smart Desk Mat Harmony,"**Denise from East Stephen, Nevada – 19 years ..."
1,Electronics,Headphones,18-25,{'uuid': '17a19f6d-3124-47fd-982a-c63976f893fa...,4,structured with bullet points,BassWave X1,- **Product:** BassWave X1 \n- **Location:** ...

### 📊 Analyze the generated data

- Data Designer automatically generates a basic statistical analysis of the generated data.

- This analysis is available via the `analysis` property of generation result objects.

In [12]:
# Print the analysis as a table.
preview.analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2                               │ 8                               │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                    ┃       data type ┃            number unique values ┃               sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category               │          string │                      2 (100.0%) │                   category │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ product_subcategory            │          string │                      2 (100.0%) │                subcategory │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ target_age_range               │          string │                       1 (50.0%) │                   category │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ customer                       │            dict │                      2 (100.0%) │          person_from_faker │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ number_of_stars                │             int │                      2 (100.0%) │                    uniform │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ review_style                   │          string │                      2 (100.0%) │                   category │
└────────────────────────────────┴─────────────────┴─────────────────────────────────┴────────────────────────────┘


                                                📝 LLM-Text Columns
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                       ┃               ┃                            ┃     prompt tokens ┃      completion tokens ┃
┃ column name           ┃     data type ┃       number unique values ┃        per record ┃             per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_name          │        string │                 2 (100.0%) │      74.0 +/- 0.0 │            6.5 +/- 2.1 │
├───────────────────────┼───────────────┼────────────────────────────┼───────────────────┼────────────────────────┤
│ customer_review       │        string │                 2 (100.0%) │      72.5 +/- 1.5 │        544.5 +/- 393.9 │
└───────────────────────┴───────────────┴────────────────────────────┴───────────────────┴────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

### 🆙 Scale up!

- Happy with your preview data?

- Use the `create` method to submit larger Data Designer generation jobs.

In [13]:
results = data_designer.create(config_builder, num_records=10, dataset_name="tutorial-1")

[16:32:18] [INFO] 🎨 Creating Data Designer dataset

[16:32:18] [INFO] ✅ Validation passed

[16:32:18] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[16:32:18] [INFO] 🩺 Running health checks for models...

[16:32:18] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...

[16:32:18] [INFO]   |-- ✅ Passed!

[16:32:18] [INFO] ⏳ Processing batch 1 of 1

[16:32:18] [INFO] 🎲 Preparing samplers to generate 10 records across 6 columns

[16:32:18] [INFO] 📝 llm-text model config for column 'product_name'

[16:32:18] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[16:32:18] [INFO]   |-- model alias: 'nemotron-nano-v3'

[16:32:18] [INFO]   |-- model provider: 'nvidia'

[16:32:18] [INFO]   |-- inference parameters:

[16:32:18] [INFO]   |  |-- generation_type=chat-completion

[16:32:18] [INFO]   |  |-- max_parallel_requests=4

[16:32:18] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[16:32:18] [INFO]   |  |-- temperature=1.00

[16:32:18] [INFO]   |  |-- top_p=1.00

[16:32:18] [INFO]   |  |-- max_tokens=2048

[16:32:18] [INFO] ⚡️ Processing llm-text column 'product_name' with 4 concurrent workers

[16:32:18] [INFO] ⏱️ llm-text column 'product_name' will report progress after each record

[16:32:18] [INFO]   |-- 🌧️ llm-text column 'product_name' progress: 1/10 (10%) complete, 1 ok, 0 failed, 3.30 rec/s, eta 2.7s

[16:32:19] [INFO]   |-- 🌧️ llm-text column 'product_name' progress: 2/10 (20%) complete, 2 ok, 0 failed, 4.91 rec/s, eta 1.6s

[16:32:19] [INFO]   |-- 🌦️ llm-text column 'product_name' progress: 3/10 (30%) complete, 3 ok, 0 failed, 7.25 rec/s, eta 1.0s

[16:32:19] [INFO]   |-- 🌦️ llm-text column 'product_name' progress: 4/10 (40%) complete, 4 ok, 0 failed, 9.42 rec/s, eta 0.6s

[16:32:19] [INFO]   |-- ⛅ llm-text column 'product_name' progress: 5/10 (50%) complete, 5 ok, 0 failed, 8.03 rec/s, eta 0.6s

[16:32:19] [INFO]   |-- ⛅ llm-text column 'product_name' progress: 6/10 (60%) complete, 6 ok, 0 failed, 8.41 rec/s, eta 0.5s

[16:32:19] [INFO]   |-- ⛅ llm-text column 'product_name' progress: 7/10 (70%) complete, 7 ok, 0 failed, 9.75 rec/s, eta 0.3s

[16:32:19] [INFO]   |-- 🌤️ llm-text column 'product_name' progress: 8/10 (80%) complete, 8 ok, 0 failed, 9.70 rec/s, eta 0.2s

[16:32:19] [INFO]   |-- 🌤️ llm-text column 'product_name' progress: 9/10 (90%) complete, 9 ok, 0 failed, 9.59 rec/s, eta 0.1s

[16:32:19] [INFO]   |-- ☀️ llm-text column 'product_name' progress: 10/10 (100%) complete, 10 ok, 0 failed, 9.73 rec/s, eta 0.0s

[16:32:19] [INFO] 📝 llm-text model config for column 'customer_review'

[16:32:19] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[16:32:19] [INFO]   |-- model alias: 'nemotron-nano-v3'

[16:32:19] [INFO]   |-- model provider: 'nvidia'

[16:32:19] [INFO]   |-- inference parameters:

[16:32:19] [INFO]   |  |-- generation_type=chat-completion

[16:32:19] [INFO]   |  |-- max_parallel_requests=4

[16:32:19] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[16:32:19] [INFO]   |  |-- temperature=1.00

[16:32:19] [INFO]   |  |-- top_p=1.00

[16:32:19] [INFO]   |  |-- max_tokens=2048

[16:32:19] [INFO] ⚡️ Processing llm-text column 'customer_review' with 4 concurrent workers

[16:32:19] [INFO] ⏱️ llm-text column 'customer_review' will report progress after each record

[16:32:20] [INFO]   |-- 🌧️ llm-text column 'customer_review' progress: 1/10 (10%) complete, 1 ok, 0 failed, 2.07 rec/s, eta 4.4s

[16:32:20] [INFO]   |-- 🌧️ llm-text column 'customer_review' progress: 2/10 (20%) complete, 2 ok, 0 failed, 2.05 rec/s, eta 3.9s

[16:32:21] [INFO]   |-- 🌦️ llm-text column 'customer_review' progress: 3/10 (30%) complete, 3 ok, 0 failed, 2.02 rec/s, eta 3.5s

[16:32:21] [INFO]   |-- 🌦️ llm-text column 'customer_review' progress: 4/10 (40%) complete, 4 ok, 0 failed, 1.96 rec/s, eta 3.1s

[16:32:21] [INFO]   |-- ⛅ llm-text column 'customer_review' progress: 5/10 (50%) complete, 5 ok, 0 failed, 2.23 rec/s, eta 2.2s

[16:32:23] [INFO]   |-- ⛅ llm-text column 'customer_review' progress: 6/10 (60%) complete, 6 ok, 0 failed, 1.60 rec/s, eta 2.5s

[16:32:24] [INFO]   |-- ⛅ llm-text column 'customer_review' progress: 7/10 (70%) complete, 7 ok, 0 failed, 1.56 rec/s, eta 1.9s

[16:32:24] [INFO]   |-- 🌤️ llm-text column 'customer_review' progress: 8/10 (80%) complete, 8 ok, 0 failed, 1.74 rec/s, eta 1.1s

[16:32:24] [INFO]   |-- 🌤️ llm-text column 'customer_review' progress: 9/10 (90%) complete, 9 ok, 0 failed, 1.86 rec/s, eta 0.5s

[16:32:27] [INFO]   |-- ☀️ llm-text column 'customer_review' progress: 10/10 (100%) complete, 10 ok, 0 failed, 1.22 rec/s, eta 0.0s

[16:32:28] [INFO] 📊 Model usage summary:

[16:32:28] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[16:32:28] [INFO]   |-- tokens: input=1783, output=2818, total=4601, tps=480

[16:32:28] [INFO]   |-- requests: success=20, failed=0, total=20, rpm=125

[16:32:28] [INFO] 📐 Measuring dataset column statistics:

[16:32:28] [INFO]   |-- 🎲 column: 'product_category'

[16:32:28] [INFO]   |-- 🎲 column: 'product_subcategory'

[16:32:28] [INFO]   |-- 🎲 column: 'target_age_range'

[16:32:28] [INFO]   |-- 🎲 column: 'customer'

[16:32:28] [INFO]   |-- 🎲 column: 'number_of_stars'

[16:32:28] [INFO]   |-- 🎲 column: 'review_style'

[16:32:28] [INFO]   |-- 📝 column: 'product_name'

[16:32:28] [INFO]   |-- 📝 column: 'customer_review'

In [14]:
# Load the generated dataset as a pandas DataFrame.
dataset = results.load_dataset()

dataset.head()

,product_category,product_subcategory,target_age_range,customer,number_of_stars,review_style,product_name,customer_review
0,Books,Classics,35-50,"{'age': 25, 'bachelors_field': 'no_degree', 'b...",4,brief,Timeless Tales Collector’s Edition,"⭐⭐⭐⭐☆ Beautiful artwork and sturdy build, but ..."
1,Electronics,Headphones,18-25,"{'age': 54, 'bachelors_field': 'no_degree', 'b...",4,detailed,AuraPulse ProHeadphones,**Rating: ★★★★☆ (4 out of 5) – Detailed Review...
2,Home & Kitchen,Cookware,18-25,"{'age': 59, 'bachelors_field': 'stem', 'birth_...",2,detailed,SizzleSnap Pan Set,"I’m Ivan from East Johnfurt, Arkansas. I’m 59 ..."
3,Books,Textbooks,18-25,"{'age': 27, 'bachelors_field': 'business', 'bi...",3,structured with bullet points,CampusMindspace Suite,- ★★☆☆☆ (3/5) - **Positive points:** - C...
4,Clothing,Women's Clothing,25-35,"{'age': 57, 'bachelors_field': 'no_degree', 'b...",2,rambling,Verdant lavender drape dress,"Well, here's the thing about that Verdant lave..."

In [15]:
# Load the analysis results into memory.
analysis = results.load_analysis()

analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 10                              │ 8                               │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                    ┃       data type ┃            number unique values ┃               sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category               │          string │                       4 (40.0%) │                   category │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ product_subcategory            │          string │                       6 (60.0%) │                subcategory │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ target_age_range               │          string │                       5 (50.0%) │                   category │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ customer                       │            dict │                     10 (100.0%) │          person_from_faker │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ number_of_stars                │             int │                       5 (50.0%) │                    uniform │
├────────────────────────────────┼─────────────────┼─────────────────────────────────┼────────────────────────────┤
│ review_style                   │          string │                       4 (40.0%) │                   category │
└────────────────────────────────┴─────────────────┴─────────────────────────────────┴────────────────────────────┘


                                                📝 LLM-Text Columns
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                       ┃               ┃                            ┃     prompt tokens ┃      completion tokens ┃
┃ column name           ┃     data type ┃       number unique values ┃        per record ┃             per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_name          │        string │                10 (100.0%) │      74.0 +/- 0.8 │            6.0 +/- 1.5 │
├───────────────────────┼───────────────┼────────────────────────────┼───────────────────┼────────────────────────┤
│ customer_review       │        string │                10 (100.0%) │      70.0 +/- 1.8 │        158.0 +/- 287.9 │
└───────────────────────┴───────────────┴────────────────────────────┴───────────────────┴────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

## ⏭️ Next Steps

Now that you've seen the basics of Data Designer, check out the following notebooks to learn more about:

- [Structured outputs and jinja expressions](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/2-structured-outputs-and-jinja-expressions/)

- [Seeding synthetic data generation with an external dataset](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/3-seeding-with-a-dataset/)

- [Providing images as context](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/4-providing-images-as-context/)

- [Generating images](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/5-generating-images/)