# 🎨 Data Designer Tutorial: Structured Outputs, Jinja Expressions, and Conditional Generation

#### 📚 What you'll learn

In this notebook, we will continue our exploration of Data Designer, demonstrating more advanced data generation using structured outputs, Jinja expressions, and conditional generation with `skip.when`.

If this is your first time using Data Designer, we recommend starting with the [first notebook](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/1-the-basics/) in this tutorial series.

### 📦 Import Data Designer

- `data_designer.config` provides access to the configuration API.

- `DataDesigner` is the main interface for data generation.

In [1]:
import data_designer.config as dd
from data_designer.interface import DataDesigner

### ⚙️ Initialize the Data Designer interface

- `DataDesigner` is the main object that is used to interface with the library.

- When initialized without arguments, the [default model providers](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) are used.

In [2]:
data_designer = DataDesigner()

### 🎛️ Define model configurations

- Each `ModelConfig` defines a model that can be used during the generation process.

- The "model alias" is used to reference the model in the Data Designer config (as we will see below).

- The "model provider" is the external service that hosts the model (see the [model config](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) docs for more details).

- By default, we use [build.nvidia.com](https://build.nvidia.com/models) as the model provider.

In [3]:
# This name is set in the model provider configuration.
MODEL_PROVIDER = "nvidia"

# The model ID is from build.nvidia.com.
MODEL_ID = "nvidia/nemotron-3-nano-30b-a3b"

# We choose this alias to be descriptive for our use case.
MODEL_ALIAS = "nemotron-nano-v3"

model_configs = [
    dd.ModelConfig(
        alias=MODEL_ALIAS,
        model=MODEL_ID,
        provider=MODEL_PROVIDER,
        inference_parameters=dd.ChatCompletionInferenceParams(
            temperature=1.0,
            top_p=1.0,
            max_tokens=2048,
            extra_body={"chat_template_kwargs": {"enable_thinking": False}},
        ),
    )
]

### 🏗️ Initialize the Data Designer Config Builder

- The Data Designer config defines the dataset schema and generation process.

- The config builder provides an intuitive interface for building this configuration.

- The list of model configs is provided to the builder at initialization.

In [4]:
config_builder = dd.DataDesignerConfigBuilder(model_configs=model_configs)

### 🧑‍🎨 Designing our data

- We will again create a product review dataset, but this time we will use structured outputs and Jinja expressions.

- Structured outputs let you specify the exact schema of the data you want to generate.

- Data Designer supports schemas specified using either json schema or Pydantic data models (recommended).

<br>

We'll define our structured outputs using [Pydantic](https://docs.pydantic.dev/latest/) data models

> 💡 **Why Pydantic?**
>
> - Pydantic models provide better IDE support and type validation.
>
> - They are more Pythonic than raw JSON schemas.
>
> - They integrate seamlessly with Data Designer's structured output system.

In [5]:
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, Field


# We define a Product schema so that the name, description, and price are generated
# in one go, with the types and constraints specified.
class Product(BaseModel):
    name: str = Field(description="The name of the product")
    description: str = Field(description="A description of the product")
    price: Decimal = Field(description="The price of the product", ge=10, le=1000, decimal_places=2)


class ProductReview(BaseModel):
    rating: int = Field(description="The rating of the product", ge=1, le=5)
    customer_mood: Literal["irritated", "mad", "happy", "neutral", "excited"] = Field(
        description="The mood of the customer"
    )
    review: str = Field(description="A review of the product")

Next, let's design our product review dataset using a few more tricks compared to the previous notebook.

In [6]:
# Since we often only want a few attributes from Person objects, we can
# set drop=True in the column config to drop the column from the final dataset.
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="customer",
        sampler_type=dd.SamplerType.PERSON_FROM_FAKER,
        params=dd.PersonFromFakerSamplerParams(),
        drop=True,
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="product_category",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(
            values=[
                "Electronics",
                "Clothing",
                "Home & Kitchen",
                "Books",
                "Home Office",
            ],
        ),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="product_subcategory",
        sampler_type=dd.SamplerType.SUBCATEGORY,
        params=dd.SubcategorySamplerParams(
            category="product_category",
            values={
                "Electronics": [
                    "Smartphones",
                    "Laptops",
                    "Headphones",
                    "Cameras",
                    "Accessories",
                ],
                "Clothing": [
                    "Men's Clothing",
                    "Women's Clothing",
                    "Winter Coats",
                    "Activewear",
                    "Accessories",
                ],
                "Home & Kitchen": [
                    "Appliances",
                    "Cookware",
                    "Furniture",
                    "Decor",
                    "Organization",
                ],
                "Books": [
                    "Fiction",
                    "Non-Fiction",
                    "Self-Help",
                    "Textbooks",
                    "Classics",
                ],
                "Home Office": [
                    "Desks",
                    "Chairs",
                    "Storage",
                    "Office Supplies",
                    "Lighting",
                ],
            },
        ),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="target_age_range",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(values=["18-25", "25-35", "35-50", "50-65", "65+"]),
    )
)

# Sampler columns support conditional params, which are used if the condition is met.
# In this example, we set the review style to rambling if the target age range is 18-25.
# Note conditional parameters are only supported for Sampler column types.
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="review_style",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(
            values=["rambling", "brief", "detailed", "structured with bullet points"],
            weights=[1, 2, 2, 1],
        ),
        conditional_params={
            "target_age_range == '18-25'": dd.CategorySamplerParams(values=["rambling"]),
        },
    )
)

# Optionally validate that the columns are configured correctly.
data_designer.validate(config_builder)

[03:20:30] [INFO] ✅ Validation passed

Next, we will use more advanced Jinja expressions to create new columns.

Jinja expressions let you:

- Access nested attributes: `{{ customer.first_name }}`

- Combine values: `{{ customer.first_name }} {{ customer.last_name }}`

- Use conditional logic: `{% if condition %}...{% endif %}`

In [7]:
# We can create new columns using Jinja expressions that reference
# existing columns, including attributes of nested objects.
config_builder.add_column(
    dd.ExpressionColumnConfig(name="customer_name", expr="{{ customer.first_name }} {{ customer.last_name }}")
)

config_builder.add_column(dd.ExpressionColumnConfig(name="customer_age", expr="{{ customer.age }}"))

config_builder.add_column(
    dd.LLMStructuredColumnConfig(
        name="product",
        prompt=(
            "Create a product in the '{{ product_category }}' category, focusing on products  "
            "related to '{{ product_subcategory }}'. The target age range of the ideal customer is "
            "{{ target_age_range }} years old. The product should be priced between $10 and $1000."
        ),
        output_format=Product,
        model_alias=MODEL_ALIAS,
    )
)

# We can even use if/else logic in our Jinja expressions to create more complex prompt patterns.
config_builder.add_column(
    dd.LLMStructuredColumnConfig(
        name="customer_review",
        prompt=(
            "Your task is to write a review for the following product:\n\n"
            "Product Name: {{ product.name }}\n"
            "Product Description: {{ product.description }}\n"
            "Price: {{ product.price }}\n\n"
            "Imagine your name is {{ customer_name }} and you are from {{ customer.city }}, {{ customer.state }}. "
            "Write the review in a style that is '{{ review_style }}'."
            "{% if target_age_range == '18-25' %}"
            "Make sure the review is more informal and conversational.\n"
            "{% else %}"
            "Make sure the review is more formal and structured.\n"
            "{% endif %}"
            "The review field should contain only the review, no other text."
        ),
        output_format=ProductReview,
        model_alias=MODEL_ALIAS,
    )
)

data_designer.validate(config_builder)

[03:20:30] [INFO] ✅ Validation passed

## 🚦 Conditional generation with `skip.when`

So far, every column is generated for every row. But sometimes an expensive LLM column only makes sense
for a subset of rows — for example, a detailed complaint analysis is only useful when the review is negative.

Data Designer lets you **skip** column generation on a per-row basis using `SkipConfig`.
Skipped rows receive `None` by default, but you can provide a sentinel value with
`skip=dd.SkipConfig(when="...", value="N/A")` to write a specific value instead.

There are three patterns to know:

| Pattern | How | Effect |
|---|---|---|
| **Expression gate** | `skip=dd.SkipConfig(when="...")` | Skip this column when the Jinja2 expression is truthy |
| **Skip propagation** (default) | Downstream column depends on a skipped column | Automatically skipped too (`propagate_skip=True` by default) |
| **Propagation opt-out** | `propagate_skip=False` on the downstream column | Always generates, even if an upstream was skipped |

**Pattern 1 — Expression gate.** Only generate a detailed complaint analysis when the customer gave a low rating (1 or 2 stars).
Rows where the rating is 3 or higher will get `None` for this column.

In [8]:
config_builder.add_column(
    dd.LLMTextColumnConfig(
        name="complaint_analysis",
        model_alias=MODEL_ALIAS,
        prompt=(
            "A customer reviewed '{{ product.name }}' ({{ product_category }} / {{ product_subcategory }}).\n\n"
            "Review: {{ customer_review.review }}\n"
            "Rating: {{ customer_review.rating }}/5\n"
            "Mood: {{ customer_review.customer_mood }}\n\n"
            "Write a short root-cause analysis of why this customer is unhappy "
            "and suggest one concrete improvement the product team could make."
        ),
        skip=dd.SkipConfig(when="{{ customer_review.rating > 2 }}"),
    )
)

DataDesignerConfigBuilder(
    sampler_columns: [
        "customer",
        "product_category",
        "product_subcategory",
        "target_age_range",
        "review_style"
    ]
    llm_text_columns: ['complaint_analysis']
    llm_structured_columns: ['product', 'customer_review']
    expression_columns: ['customer_name', 'customer_age']
)

**Pattern 2 — Skip propagation.** `action_items` depends on `complaint_analysis`.
When `complaint_analysis` is skipped, `action_items` auto-skips too because
`propagate_skip` defaults to `True`.

In [9]:
config_builder.add_column(
    dd.LLMTextColumnConfig(
        name="action_items",
        model_alias=MODEL_ALIAS,
        prompt=(
            "Based on this complaint analysis:\n"
            "{{ complaint_analysis }}\n\n"
            "List 2-3 concrete action items for the product team."
        ),
    )
)

DataDesignerConfigBuilder(
    sampler_columns: [
        "customer",
        "product_category",
        "product_subcategory",
        "target_age_range",
        "review_style"
    ]
    llm_text_columns: ['complaint_analysis', 'action_items']
    llm_structured_columns: ['product', 'customer_review']
    expression_columns: ['customer_name', 'customer_age']
)

**Pattern 3 — Propagation opt-out.** `review_summary` also depends on `complaint_analysis`,
but sets `propagate_skip=False` so it always generates. The prompt uses a Jinja conditional
to handle the case where `complaint_analysis` is `None`.

In [10]:
config_builder.add_column(
    dd.LLMTextColumnConfig(
        name="review_summary",
        model_alias=MODEL_ALIAS,
        propagate_skip=False,
        prompt=(
            "Summarize this product review in one sentence:\n"
            "Product: {{ product.name }}\n"
            "Rating: {{ customer_review.rating }}/5\n"
            "Review: {{ customer_review.review }}\n"
            "{% if complaint_analysis %}"
            "Complaint analysis: {{ complaint_analysis }}\n"
            "{% endif %}"
        ),
    )
)

data_designer.validate(config_builder)

[03:20:30] [INFO] ✅ Validation passed

### 🔁 Iteration is key – preview the dataset!

1. Use the `preview` method to generate a sample of records quickly.

2. Inspect the results for quality and format issues.

3. Adjust column configurations, prompts, or parameters as needed.

4. Re-run the preview until satisfied.

In [11]:
preview = data_designer.preview(config_builder, num_records=2)

[03:20:30] [INFO] 🎥 Preview generation in progress

[03:20:30] [INFO]   |-- 🔒 Jinja rendering engine: secure

[03:20:30] [INFO] ✅ Validation passed

[03:20:30] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[03:20:30] [INFO] 🩺 Running health checks for models...

[03:20:30] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...

[03:20:31] [INFO]   |-- ✅ Passed!

[03:20:31] [INFO] 🎲 Preparing samplers to generate 2 records across 5 columns

[03:20:31] [INFO] 🧩 Generating column `customer_name` from expression

[03:20:31] [INFO] 🧩 Generating column `customer_age` from expression

[03:20:31] [INFO] 🗂️ llm-structured model config for column 'product'

[03:20:31] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:31] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:31] [INFO]   |-- model provider: 'nvidia'

[03:20:31] [INFO]   |-- inference parameters:

[03:20:31] [INFO]   |  |-- generation_type=chat-completion

[03:20:31] [INFO]   |  |-- max_parallel_requests=4

[03:20:31] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:31] [INFO]   |  |-- temperature=1.00

[03:20:31] [INFO]   |  |-- top_p=1.00

[03:20:31] [INFO]   |  |-- max_tokens=2048

[03:20:31] [INFO] ⚡️ Processing llm-structured column 'product' with 4 concurrent workers

[03:20:31] [INFO] ⏱️ llm-structured column 'product' will report progress after each record

[03:20:32] [INFO]   |-- 🐥 llm-structured column 'product' progress: 1/2 (50%) complete, 1 ok, 0 failed, 0.98 rec/s, eta 1.0s

[03:20:32] [INFO]   |-- 🐔 llm-structured column 'product' progress: 2/2 (100%) complete, 2 ok, 0 failed, 1.66 rec/s, eta 0.0s

[03:20:32] [INFO] 🗂️ llm-structured model config for column 'customer_review'

[03:20:32] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:32] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:32] [INFO]   |-- model provider: 'nvidia'

[03:20:32] [INFO]   |-- inference parameters:

[03:20:32] [INFO]   |  |-- generation_type=chat-completion

[03:20:32] [INFO]   |  |-- max_parallel_requests=4

[03:20:32] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:32] [INFO]   |  |-- temperature=1.00

[03:20:32] [INFO]   |  |-- top_p=1.00

[03:20:32] [INFO]   |  |-- max_tokens=2048

[03:20:32] [INFO] ⚡️ Processing llm-structured column 'customer_review' with 4 concurrent workers

[03:20:32] [INFO] ⏱️ llm-structured column 'customer_review' will report progress after each record

[03:20:33] [INFO]   |-- ⛅ llm-structured column 'customer_review' progress: 1/2 (50%) complete, 1 ok, 0 failed, 1.37 rec/s, eta 0.7s

[03:20:35] [INFO]   |-- ☀️ llm-structured column 'customer_review' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.65 rec/s, eta 0.0s

[03:20:35] [INFO] 📝 llm-text model config for column 'complaint_analysis'

[03:20:35] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:35] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:35] [INFO]   |-- model provider: 'nvidia'

[03:20:35] [INFO]   |-- inference parameters:

[03:20:35] [INFO]   |  |-- generation_type=chat-completion

[03:20:35] [INFO]   |  |-- max_parallel_requests=4

[03:20:35] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:35] [INFO]   |  |-- temperature=1.00

[03:20:35] [INFO]   |  |-- top_p=1.00

[03:20:35] [INFO]   |  |-- max_tokens=2048

[03:20:35] [INFO] ⚡️ Processing llm-text column 'complaint_analysis' with 4 concurrent workers

[03:20:35] [INFO] ⏱️ llm-text column 'complaint_analysis' will report progress after each record

[03:20:35] [INFO]   |-- 😸 llm-text column 'complaint_analysis' progress: 1/2 (50%) complete, 0 ok, 0 failed, 1 skipped, 675.07 rec/s, eta 0.0s

[03:20:35] [INFO]   |-- 🦁 llm-text column 'complaint_analysis' progress: 2/2 (100%) complete, 0 ok, 0 failed, 2 skipped, 939.94 rec/s, eta 0.0s

[03:20:35] [INFO] 📝 llm-text model config for column 'action_items'

[03:20:35] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:35] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:35] [INFO]   |-- model provider: 'nvidia'

[03:20:35] [INFO]   |-- inference parameters:

[03:20:35] [INFO]   |  |-- generation_type=chat-completion

[03:20:35] [INFO]   |  |-- max_parallel_requests=4

[03:20:35] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:35] [INFO]   |  |-- temperature=1.00

[03:20:35] [INFO]   |  |-- top_p=1.00

[03:20:35] [INFO]   |  |-- max_tokens=2048

[03:20:35] [INFO] ⚡️ Processing llm-text column 'action_items' with 4 concurrent workers

[03:20:35] [INFO] ⏱️ llm-text column 'action_items' will report progress after each record

[03:20:35] [INFO]   |-- 😸 llm-text column 'action_items' progress: 1/2 (50%) complete, 0 ok, 0 failed, 1 skipped, 1487.86 rec/s, eta 0.0s

[03:20:35] [INFO]   |-- 🦁 llm-text column 'action_items' progress: 2/2 (100%) complete, 0 ok, 0 failed, 2 skipped, 1982.73 rec/s, eta 0.0s

[03:20:35] [INFO] 📝 llm-text model config for column 'review_summary'

[03:20:35] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:35] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:35] [INFO]   |-- model provider: 'nvidia'

[03:20:35] [INFO]   |-- inference parameters:

[03:20:35] [INFO]   |  |-- generation_type=chat-completion

[03:20:35] [INFO]   |  |-- max_parallel_requests=4

[03:20:35] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:35] [INFO]   |  |-- temperature=1.00

[03:20:35] [INFO]   |  |-- top_p=1.00

[03:20:35] [INFO]   |  |-- max_tokens=2048

[03:20:35] [INFO] ⚡️ Processing llm-text column 'review_summary' with 4 concurrent workers

[03:20:35] [INFO] ⏱️ llm-text column 'review_summary' will report progress after each record

[03:20:35] [INFO]   |-- ⛅ llm-text column 'review_summary' progress: 1/2 (50%) complete, 1 ok, 0 failed, 2.01 rec/s, eta 0.5s

[03:20:36] [INFO]   |-- ☀️ llm-text column 'review_summary' progress: 2/2 (100%) complete, 2 ok, 0 failed, 3.15 rec/s, eta 0.0s

[03:20:36] [INFO] 📊 Model usage summary:

[03:20:36] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[03:20:36] [INFO]   |-- tokens: input=1946, output=893, total=2839, tps=547

[03:20:36] [INFO]   |-- requests: success=6, failed=0, total=6, rpm=69

[03:20:36] [INFO] 🙈 Dropping columns: ['customer']

[03:20:36] [INFO] 📐 Measuring dataset column statistics:

[03:20:36] [INFO]   |-- 🎲 column: 'product_category'

[03:20:36] [INFO]   |-- 🎲 column: 'product_subcategory'

[03:20:36] [INFO]   |-- 🎲 column: 'target_age_range'

[03:20:36] [INFO]   |-- 🎲 column: 'review_style'

[03:20:36] [INFO]   |-- 🧩 column: 'customer_name'

[03:20:36] [INFO]   |-- 🧩 column: 'customer_age'

[03:20:36] [INFO]   |-- 🗂️ column: 'product'

[03:20:36] [INFO]   |-- 🗂️ column: 'customer_review'

[03:20:36] [INFO]   |-- 📝 column: 'complaint_analysis'

[03:20:36] [INFO]   |-- 📝 column: 'action_items'

[03:20:36] [INFO]   |-- 📝 column: 'review_summary'

[03:20:36] [INFO] 🏆 Preview complete!

In [12]:
# Run this cell multiple times to cycle through the 2 preview records.
# Look for rows where complaint_analysis and action_items are None (skipped)
# vs rows where they were generated (low-rated reviews).
preview.display_sample_record()

                                              Generated Columns
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                ┃ Value                                                                                ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category    │ Books                                                                                │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ product_subcategory │ Fiction                                                                              │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ target_age_range    │ 18-25                                                                                │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ review_style        │ rambling                                                                             │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ complaint_analysis  │ None                                                                                 │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ action_items        │ None                                                                                 │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ review_summary      │ A vivid, poetic blend of interconnected turn‑of‑the‑century teen tales that captures │
│                     │ late‑night digital angst and wonder in a few coffee‑break‑length stories.            │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ product             │ {                                                                                    │
│                     │     'name': 'Midnight Musings: Turn-of-the-Century Teen Tales',                      │
│                     │     'description': "A collection of contemporary short fiction that captures the     │
│                     │ eclectic voice of today's 18-25 crowd, exploring themes of identity, digital         │
│                     │ alienation, and fleeting moments of wonder. Each story is a literary companion for   │
│                     │ late-night reading sessions, coffeehouse reflections, and classroom discussions,     │
│                     │ blending lyrical prose with relatable, modern narratives that resonate with emerging │
│                     │ adults.",                                                                            │
│                     │     'price': 24.99                                                                   │
│                     │ }                                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer_review     │ {                                                                                    │
│                     │     'rating': 4,                                                                     │
│                     │     'customer_mood': 'happy',                                                        │
│                     │     'review': "Alrighty, so I just finished Midnight Musings and wow, what a ride.   │
│                     │ I’m sitting here in my little Lanefort apartment at 2 a.m., coffee half-cold, and I  │
│                     │ can't help but just... keep thinking about the stories. Like, the way the author     │
│                     │ manages to capture these super‑relatable moments of digital alienation? It's like    │
│                     │ they peeked into my group chat and wrote it down. I mean, honestly, how many times   │
│                     │ can you scroll through memes before you start questioning your entire existence? But │
│                     │ the book didn't just stop there—there were these tiny, glittering scenes of wonder   │
│                     │ that made me pause, stare at the ceiling, and wonder if maybe I’m not as lost as I   │
│                     │ thought. The syntax is lyrical, but not pretentious—just enough poetic sparkle to    │
│                     │ make the prose feel like a late‑night whisper in a coffee shop where everyone's      │
│                     │ half‑asleep and half‑alive. I loved the way each story feels like a postcard from a  │
│                     │ different corner of the internet, yet somehow ties back to that universal            │
│                     │ teen‑to‑young‑adult angst we all carry. It feels personal, like a mixtape of stories │
│                     │ that you can actually read in one sitting and still feel like you’ve been handed a   │
│                     │ mixtape of life lessons. I squeezed it into a single coffee break and came out       │
│                     │ feeling a little more… whole? Maybe it’s the caffeine, maybe it’s the stories, but   │
│                     │ I’m definitely glad I bought it. If you’re looking for something that speaks your    │
│                     │ language, that gets your late‑night hustle, and maybe even gives you a fresh         │
│                     │ perspective on why you’re still scrolling at 3 a.m., this is it. 5 stars would be    │
│                     │ too high, but 4 feels about right—just enough to keep me dreaming about the next     │
│                     │ midnight reading session."                                                           │
│                     │ }                                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer_name       │ Brittany White                                                                       │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer_age        │ 27                                                                                   │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┘

In [13]:
# The preview dataset is available as a pandas DataFrame.
# Notice that complaint_analysis, action_items, and review_summary columns
# reflect the skip behavior: None for skipped rows, generated text otherwise.
preview.dataset

,product_category,product_subcategory,target_age_range,review_style,customer_name,customer_age,product,customer_review,complaint_analysis,action_items,review_summary
0,Books,Fiction,18-25,rambling,Brittany White,27,{'name': 'Midnight Musings: Turn-of-the-Centur...,"{'rating': 4, 'customer_mood': 'happy', 'revie...",None,None,"A vivid, poetic blend of interconnected turn‑o..."
1,Home Office,Lighting,50-65,structured with bullet points,Steven Russell,79,{'name': 'Tabletop Daylight 3000 Lux Adjustabl...,"{'rating': 5, 'customer_mood': 'happy', 'revie...",None,None,I highly recommend the Tabletop Daylight 3000 ...

### 📊 Analyze the generated data

- Data Designer automatically generates a basic statistical analysis of the generated data.

- This analysis is available via the `analysis` property of generation result objects.

In [14]:
# Print the analysis as a table.
preview.analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2                               │ 11                              │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                      ┃        data type ┃               number unique values ┃         sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category                 │           string │                         2 (100.0%) │             category │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ product_subcategory              │           string │                         2 (100.0%) │          subcategory │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ target_age_range                 │           string │                         2 (100.0%) │             category │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ review_style                     │           string │                         2 (100.0%) │             category │
└──────────────────────────────────┴──────────────────┴────────────────────────────────────┴──────────────────────┘


                                                📝 LLM-Text Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃                         ┃              ┃                           ┃       prompt tokens ┃    completion tokens ┃
┃ column name             ┃    data type ┃      number unique values ┃          per record ┃           per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ complaint_analysis      │         None │                  0 (0.0%) │     281.0 +/- 155.0 │          1.0 +/- 0.0 │
├─────────────────────────┼──────────────┼───────────────────────────┼─────────────────────┼──────────────────────┤
│ action_items            │         None │                  0 (0.0%) │        22.0 +/- 0.0 │          1.0 +/- 0.0 │
├─────────────────────────┼──────────────┼───────────────────────────┼─────────────────────┼──────────────────────┤
│ review_summary          │       string │                2 (100.0%) │     254.0 +/- 155.0 │        45.0 +/- 12.7 │
└─────────────────────────┴──────────────┴───────────────────────────┴─────────────────────┴──────────────────────┘


                                             🗂️ LLM-Structured Columns
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃                      ┃               ┃                            ┃       prompt tokens ┃     completion tokens ┃
┃ column name          ┃     data type ┃       number unique values ┃          per record ┃            per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ product              │          dict │                 2 (100.0%) │       264.5 +/- 0.5 │        119.0 +/- 25.5 │
├──────────────────────┼───────────────┼────────────────────────────┼─────────────────────┼───────────────────────┤
│ customer_review      │          dict │                 2 (100.0%) │      375.5 +/- 19.5 │       240.0 +/- 216.4 │
└──────────────────────┴───────────────┴────────────────────────────┴─────────────────────┴───────────────────────┘


                                               🧩 Expression Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                       ┃                data type ┃                             number unique values ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ customer_name                     │                   string │                                       2 (100.0%) │
├───────────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────────┤
│ customer_age                      │                   string │                                       2 (100.0%) │
└───────────────────────────────────┴──────────────────────────┴──────────────────────────────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

### 🆙 Scale up!

- Happy with your preview data?

- Use the `create` method to submit larger Data Designer generation jobs.

In [15]:
results = data_designer.create(config_builder, num_records=10, dataset_name="tutorial-2")

[03:20:36] [INFO] 🎨 Creating Data Designer dataset

[03:20:36] [INFO]   |-- 🔒 Jinja rendering engine: secure

[03:20:36] [INFO] ✅ Validation passed

[03:20:36] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[03:20:36] [INFO] 🩺 Running health checks for models...

[03:20:36] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...

[03:20:36] [INFO]   |-- ✅ Passed!

[03:20:36] [INFO] ⏳ Processing batch 1 of 1

[03:20:36] [INFO] 🎲 Preparing samplers to generate 10 records across 5 columns

[03:20:36] [INFO] 🧩 Generating column `customer_name` from expression

[03:20:36] [INFO] 🧩 Generating column `customer_age` from expression

[03:20:36] [INFO] 🗂️ llm-structured model config for column 'product'

[03:20:36] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:36] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:36] [INFO]   |-- model provider: 'nvidia'

[03:20:36] [INFO]   |-- inference parameters:

[03:20:36] [INFO]   |  |-- generation_type=chat-completion

[03:20:36] [INFO]   |  |-- max_parallel_requests=4

[03:20:36] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:36] [INFO]   |  |-- temperature=1.00

[03:20:36] [INFO]   |  |-- top_p=1.00

[03:20:36] [INFO]   |  |-- max_tokens=2048

[03:20:36] [INFO] ⚡️ Processing llm-structured column 'product' with 4 concurrent workers

[03:20:36] [INFO] ⏱️ llm-structured column 'product' will report progress after each record

[03:20:37] [INFO]   |-- 🌧️ llm-structured column 'product' progress: 1/10 (10%) complete, 1 ok, 0 failed, 1.34 rec/s, eta 6.7s

[03:20:37] [INFO]   |-- 🌧️ llm-structured column 'product' progress: 2/10 (20%) complete, 2 ok, 0 failed, 2.35 rec/s, eta 3.4s

[03:20:38] [INFO]   |-- 🌦️ llm-structured column 'product' progress: 3/10 (30%) complete, 3 ok, 0 failed, 2.64 rec/s, eta 2.6s

[03:20:38] [INFO]   |-- 🌦️ llm-structured column 'product' progress: 4/10 (40%) complete, 4 ok, 0 failed, 2.81 rec/s, eta 2.1s

[03:20:38] [INFO]   |-- ⛅ llm-structured column 'product' progress: 5/10 (50%) complete, 5 ok, 0 failed, 3.43 rec/s, eta 1.5s

[03:20:38] [INFO]   |-- ⛅ llm-structured column 'product' progress: 6/10 (60%) complete, 6 ok, 0 failed, 3.60 rec/s, eta 1.1s

[03:20:39] [INFO]   |-- ⛅ llm-structured column 'product' progress: 7/10 (70%) complete, 7 ok, 0 failed, 3.25 rec/s, eta 0.9s

[03:20:39] [INFO]   |-- 🌤️ llm-structured column 'product' progress: 8/10 (80%) complete, 8 ok, 0 failed, 3.55 rec/s, eta 0.6s

[03:20:39] [INFO]   |-- 🌤️ llm-structured column 'product' progress: 9/10 (90%) complete, 9 ok, 0 failed, 3.98 rec/s, eta 0.3s

[03:20:39] [INFO]   |-- ☀️ llm-structured column 'product' progress: 10/10 (100%) complete, 10 ok, 0 failed, 3.77 rec/s, eta 0.0s

[03:20:39] [INFO] 🗂️ llm-structured model config for column 'customer_review'

[03:20:39] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:39] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:39] [INFO]   |-- model provider: 'nvidia'

[03:20:39] [INFO]   |-- inference parameters:

[03:20:39] [INFO]   |  |-- generation_type=chat-completion

[03:20:39] [INFO]   |  |-- max_parallel_requests=4

[03:20:39] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:39] [INFO]   |  |-- temperature=1.00

[03:20:39] [INFO]   |  |-- top_p=1.00

[03:20:39] [INFO]   |  |-- max_tokens=2048

[03:20:39] [INFO] ⚡️ Processing llm-structured column 'customer_review' with 4 concurrent workers

[03:20:39] [INFO] ⏱️ llm-structured column 'customer_review' will report progress after each record

[03:20:40] [INFO]   |-- 🌑 llm-structured column 'customer_review' progress: 1/10 (10%) complete, 1 ok, 0 failed, 0.74 rec/s, eta 12.1s

[03:20:41] [INFO]   |-- 🌑 llm-structured column 'customer_review' progress: 2/10 (20%) complete, 2 ok, 0 failed, 1.30 rec/s, eta 6.2s

[03:20:41] [INFO]   |-- 🌘 llm-structured column 'customer_review' progress: 3/10 (30%) complete, 3 ok, 0 failed, 1.75 rec/s, eta 4.0s

[03:20:41] [INFO]   |-- 🌘 llm-structured column 'customer_review' progress: 4/10 (40%) complete, 4 ok, 0 failed, 2.28 rec/s, eta 2.6s

[03:20:41] [INFO]   |-- 🌗 llm-structured column 'customer_review' progress: 5/10 (50%) complete, 5 ok, 0 failed, 2.13 rec/s, eta 2.3s

[03:20:42] [INFO]   |-- 🌗 llm-structured column 'customer_review' progress: 6/10 (60%) complete, 6 ok, 0 failed, 2.38 rec/s, eta 1.7s

[03:20:42] [INFO]   |-- 🌗 llm-structured column 'customer_review' progress: 7/10 (70%) complete, 7 ok, 0 failed, 2.10 rec/s, eta 1.4s

[03:20:44] [INFO]   |-- 🌖 llm-structured column 'customer_review' progress: 8/10 (80%) complete, 8 ok, 0 failed, 1.78 rec/s, eta 1.1s

[03:20:44] [INFO]   |-- 🌖 llm-structured column 'customer_review' progress: 9/10 (90%) complete, 9 ok, 0 failed, 1.75 rec/s, eta 0.6s

[03:20:46] [INFO]   |-- 🌕 llm-structured column 'customer_review' progress: 10/10 (100%) complete, 10 ok, 0 failed, 1.51 rec/s, eta 0.0s

[03:20:46] [INFO] 📝 llm-text model config for column 'complaint_analysis'

[03:20:46] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:46] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:46] [INFO]   |-- model provider: 'nvidia'

[03:20:46] [INFO]   |-- inference parameters:

[03:20:46] [INFO]   |  |-- generation_type=chat-completion

[03:20:46] [INFO]   |  |-- max_parallel_requests=4

[03:20:46] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:46] [INFO]   |  |-- temperature=1.00

[03:20:46] [INFO]   |  |-- top_p=1.00

[03:20:46] [INFO]   |  |-- max_tokens=2048

[03:20:46] [INFO] ⚡️ Processing llm-text column 'complaint_analysis' with 4 concurrent workers

[03:20:46] [INFO] ⏱️ llm-text column 'complaint_analysis' will report progress after each record

[03:20:46] [INFO]   |-- 🐱 llm-text column 'complaint_analysis' progress: 1/10 (10%) complete, 0 ok, 0 failed, 1 skipped, 883.44 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 🐱 llm-text column 'complaint_analysis' progress: 2/10 (20%) complete, 0 ok, 0 failed, 2 skipped, 1220.23 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😺 llm-text column 'complaint_analysis' progress: 3/10 (30%) complete, 0 ok, 0 failed, 3 skipped, 1402.11 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😺 llm-text column 'complaint_analysis' progress: 4/10 (40%) complete, 0 ok, 0 failed, 4 skipped, 1498.22 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😸 llm-text column 'complaint_analysis' progress: 5/10 (50%) complete, 0 ok, 0 failed, 5 skipped, 1548.37 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😸 llm-text column 'complaint_analysis' progress: 6/10 (60%) complete, 0 ok, 0 failed, 6 skipped, 1596.01 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😸 llm-text column 'complaint_analysis' progress: 7/10 (70%) complete, 0 ok, 0 failed, 7 skipped, 1619.14 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😼 llm-text column 'complaint_analysis' progress: 8/10 (80%) complete, 0 ok, 0 failed, 8 skipped, 1651.36 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😼 llm-text column 'complaint_analysis' progress: 9/10 (90%) complete, 0 ok, 0 failed, 9 skipped, 1657.71 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 🦁 llm-text column 'complaint_analysis' progress: 10/10 (100%) complete, 0 ok, 0 failed, 10 skipped, 1662.41 rec/s, eta 0.0s

[03:20:46] [INFO] 📝 llm-text model config for column 'action_items'

[03:20:46] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:46] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:46] [INFO]   |-- model provider: 'nvidia'

[03:20:46] [INFO]   |-- inference parameters:

[03:20:46] [INFO]   |  |-- generation_type=chat-completion

[03:20:46] [INFO]   |  |-- max_parallel_requests=4

[03:20:46] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:46] [INFO]   |  |-- temperature=1.00

[03:20:46] [INFO]   |  |-- top_p=1.00

[03:20:46] [INFO]   |  |-- max_tokens=2048

[03:20:46] [INFO] ⚡️ Processing llm-text column 'action_items' with 4 concurrent workers

[03:20:46] [INFO] ⏱️ llm-text column 'action_items' will report progress after each record

[03:20:46] [INFO]   |-- 😴 llm-text column 'action_items' progress: 1/10 (10%) complete, 0 ok, 0 failed, 1 skipped, 1383.72 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😴 llm-text column 'action_items' progress: 2/10 (20%) complete, 0 ok, 0 failed, 2 skipped, 1785.75 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 🥱 llm-text column 'action_items' progress: 3/10 (30%) complete, 0 ok, 0 failed, 3 skipped, 2010.53 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 🥱 llm-text column 'action_items' progress: 4/10 (40%) complete, 0 ok, 0 failed, 4 skipped, 2199.25 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😐 llm-text column 'action_items' progress: 5/10 (50%) complete, 0 ok, 0 failed, 5 skipped, 2306.87 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😐 llm-text column 'action_items' progress: 6/10 (60%) complete, 0 ok, 0 failed, 6 skipped, 2395.63 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😐 llm-text column 'action_items' progress: 7/10 (70%) complete, 0 ok, 0 failed, 7 skipped, 2449.05 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😊 llm-text column 'action_items' progress: 8/10 (80%) complete, 0 ok, 0 failed, 8 skipped, 2482.35 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 😊 llm-text column 'action_items' progress: 9/10 (90%) complete, 0 ok, 0 failed, 9 skipped, 2531.05 rec/s, eta 0.0s

[03:20:46] [INFO]   |-- 🤩 llm-text column 'action_items' progress: 10/10 (100%) complete, 0 ok, 0 failed, 10 skipped, 2140.14 rec/s, eta 0.0s

[03:20:46] [INFO] 📝 llm-text model config for column 'review_summary'

[03:20:46] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[03:20:46] [INFO]   |-- model alias: 'nemotron-nano-v3'

[03:20:46] [INFO]   |-- model provider: 'nvidia'

[03:20:46] [INFO]   |-- inference parameters:

[03:20:46] [INFO]   |  |-- generation_type=chat-completion

[03:20:46] [INFO]   |  |-- max_parallel_requests=4

[03:20:46] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[03:20:46] [INFO]   |  |-- temperature=1.00

[03:20:46] [INFO]   |  |-- top_p=1.00

[03:20:46] [INFO]   |  |-- max_tokens=2048

[03:20:46] [INFO] ⚡️ Processing llm-text column 'review_summary' with 4 concurrent workers

[03:20:46] [INFO] ⏱️ llm-text column 'review_summary' will report progress after each record

[03:20:46] [INFO]   |-- 🌑 llm-text column 'review_summary' progress: 1/10 (10%) complete, 1 ok, 0 failed, 1.69 rec/s, eta 5.3s

[03:20:46] [INFO]   |-- 🌑 llm-text column 'review_summary' progress: 2/10 (20%) complete, 2 ok, 0 failed, 3.10 rec/s, eta 2.6s

[03:20:46] [INFO]   |-- 🌘 llm-text column 'review_summary' progress: 3/10 (30%) complete, 3 ok, 0 failed, 4.62 rec/s, eta 1.5s

[03:20:47] [INFO]   |-- 🌘 llm-text column 'review_summary' progress: 4/10 (40%) complete, 4 ok, 0 failed, 5.50 rec/s, eta 1.1s

[03:20:47] [INFO]   |-- 🌗 llm-text column 'review_summary' progress: 5/10 (50%) complete, 5 ok, 0 failed, 4.55 rec/s, eta 1.1s

[03:20:47] [INFO]   |-- 🌗 llm-text column 'review_summary' progress: 6/10 (60%) complete, 6 ok, 0 failed, 5.12 rec/s, eta 0.8s

[03:20:47] [INFO]   |-- 🌗 llm-text column 'review_summary' progress: 7/10 (70%) complete, 7 ok, 0 failed, 5.17 rec/s, eta 0.6s

[03:20:47] [INFO]   |-- 🌖 llm-text column 'review_summary' progress: 8/10 (80%) complete, 8 ok, 0 failed, 5.57 rec/s, eta 0.4s

[03:20:48] [INFO]   |-- 🌖 llm-text column 'review_summary' progress: 9/10 (90%) complete, 9 ok, 0 failed, 4.80 rec/s, eta 0.2s

[03:20:48] [INFO]   |-- 🌕 llm-text column 'review_summary' progress: 10/10 (100%) complete, 10 ok, 0 failed, 5.27 rec/s, eta 0.0s

[03:20:48] [INFO] 🙈 Dropping columns: ['customer']

[03:20:48] [INFO] 📊 Model usage summary:

[03:20:48] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[03:20:48] [INFO]   |-- tokens: input=9196, output=4024, total=13220, tps=1151

[03:20:48] [INFO]   |-- requests: success=30, failed=0, total=30, rpm=156

[03:20:48] [INFO] 📐 Measuring dataset column statistics:

[03:20:48] [INFO]   |-- 🎲 column: 'product_category'

[03:20:48] [INFO]   |-- 🎲 column: 'product_subcategory'

[03:20:48] [INFO]   |-- 🎲 column: 'target_age_range'

[03:20:48] [INFO]   |-- 🎲 column: 'review_style'

[03:20:48] [INFO]   |-- 🧩 column: 'customer_name'

[03:20:48] [INFO]   |-- 🧩 column: 'customer_age'

[03:20:48] [INFO]   |-- 🗂️ column: 'product'

[03:20:48] [INFO]   |-- 🗂️ column: 'customer_review'

[03:20:48] [INFO]   |-- 📝 column: 'complaint_analysis'

[03:20:48] [INFO]   |-- 📝 column: 'action_items'

[03:20:48] [INFO]   |-- 📝 column: 'review_summary'

In [16]:
# Load the generated dataset as a pandas DataFrame.
dataset = results.load_dataset()

dataset.head()

,product_category,product_subcategory,target_age_range,review_style,customer_name,customer_age,product,customer_review,complaint_analysis,action_items,review_summary
0,Home Office,Lighting,65+,detailed,Amanda Singh,41,"{'description': 'A sleek, touch-controlled LED...","{'customer_mood': 'happy', 'rating': 5, 'revie...",None,None,A 5‑star review praising the LuminaTouch LED T...
1,Home Office,Lighting,65+,rambling,Don Lopez,69,"{'description': 'A lightweight, ergonomic desk...","{'customer_mood': 'happy', 'rating': 5, 'revie...",None,None,I highly recommend the Ultra‑Soft Adjustable W...
2,Books,Textbooks,35-50,rambling,Benjamin Cisneros,30,{'description': 'A curated collection of found...,"{'customer_mood': 'happy', 'rating': 5, 'revie...",None,None,A five‑star review lauds this book as an elega...
3,Home Office,Storage,35-50,detailed,Brian Wise,92,"{'description': 'A sleek, space-saving storage...","{'customer_mood': 'happy', 'rating': 5, 'revie...",None,None,"The ErgoHome Foldable Desk Organizer, praised ..."
4,Electronics,Headphones,35-50,detailed,Matthew Collins,37,{'description': 'Premium wireless over-ear hea...,"{'customer_mood': 'excited', 'rating': 5, 'rev...",None,None,The reviewer lauds the HS‑350 headphones as a ...

In [17]:
# Load the analysis results into memory.
analysis = results.load_analysis()

analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 10                              │ 11                              │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                      ┃        data type ┃               number unique values ┃         sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category                 │           string │                          5 (50.0%) │             category │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ product_subcategory              │           string │                          7 (70.0%) │          subcategory │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ target_age_range                 │           string │                          4 (40.0%) │             category │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ review_style                     │           string │                          3 (30.0%) │             category │
└──────────────────────────────────┴──────────────────┴────────────────────────────────────┴──────────────────────┘


                                                📝 LLM-Text Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃                         ┃              ┃                            ┃      prompt tokens ┃    completion tokens ┃
┃ column name             ┃    data type ┃       number unique values ┃         per record ┃           per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ complaint_analysis      │         None │                   0 (0.0%) │     255.5 +/- 87.0 │          1.0 +/- 0.0 │
├─────────────────────────┼──────────────┼────────────────────────────┼────────────────────┼──────────────────────┤
│ action_items            │         None │                   0 (0.0%) │       22.0 +/- 0.0 │          1.0 +/- 0.0 │
├─────────────────────────┼──────────────┼────────────────────────────┼────────────────────┼──────────────────────┤
│ review_summary          │       string │                10 (100.0%) │     228.5 +/- 86.7 │         47.0 +/- 9.4 │
└─────────────────────────┴──────────────┴────────────────────────────┴────────────────────┴──────────────────────┘


                                             🗂️ LLM-Structured Columns
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃                      ┃               ┃                            ┃       prompt tokens ┃     completion tokens ┃
┃ column name          ┃     data type ┃       number unique values ┃          per record ┃            per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ product              │          dict │                10 (100.0%) │       264.0 +/- 0.7 │         92.0 +/- 21.9 │
├──────────────────────┼───────────────┼────────────────────────────┼─────────────────────┼───────────────────────┤
│ customer_review      │          dict │                10 (100.0%) │      347.0 +/- 21.1 │        213.0 +/- 91.6 │
└──────────────────────┴───────────────┴────────────────────────────┴─────────────────────┴───────────────────────┘


                                               🧩 Expression Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                       ┃                data type ┃                             number unique values ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ customer_name                     │                   string │                                      10 (100.0%) │
├───────────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────────┤
│ customer_age                      │                   string │                                      10 (100.0%) │
└───────────────────────────────────┴──────────────────────────┴──────────────────────────────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

## ⏭️ Next Steps

Check out the following notebook to learn more about:

- [Seeding synthetic data generation with an external dataset](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/3-seeding-with-a-dataset/)

- [Providing images as context](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/4-providing-images-as-context/)

- [Generating images](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/5-generating-images/)