# 🎨 Data Designer Tutorial: Structured Outputs and Jinja Expressions

#### 📚 What you'll learn

In this notebook, we will continue our exploration of Data Designer, demonstrating more advanced data generation using structured outputs and Jinja expressions.

If this is your first time using Data Designer, we recommend starting with the [first notebook](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/1-the-basics/) in this tutorial series.

### 📦 Import Data Designer

- `data_designer.config` provides access to the configuration API.

- `DataDesigner` is the main interface for data generation.

In [1]:
import data_designer.config as dd
from data_designer.interface import DataDesigner

### ⚙️ Initialize the Data Designer interface

- `DataDesigner` is the main object that is used to interface with the library.

- When initialized without arguments, the [default model providers](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) are used.

In [2]:
data_designer = DataDesigner()

### 🎛️ Define model configurations

- Each `ModelConfig` defines a model that can be used during the generation process.

- The "model alias" is used to reference the model in the Data Designer config (as we will see below).

- The "model provider" is the external service that hosts the model (see the [model config](https://nvidia-nemo.github.io/DataDesigner/latest/concepts/models/default-model-settings/) docs for more details).

- By default, we use [build.nvidia.com](https://build.nvidia.com/models) as the model provider.

In [3]:
# This name is set in the model provider configuration.
MODEL_PROVIDER = "nvidia"

# The model ID is from build.nvidia.com.
MODEL_ID = "nvidia/nemotron-3-nano-30b-a3b"

# We choose this alias to be descriptive for our use case.
MODEL_ALIAS = "nemotron-nano-v3"

model_configs = [
    dd.ModelConfig(
        alias=MODEL_ALIAS,
        model=MODEL_ID,
        provider=MODEL_PROVIDER,
        inference_parameters=dd.ChatCompletionInferenceParams(
            temperature=1.0,
            top_p=1.0,
            max_tokens=2048,
            extra_body={"chat_template_kwargs": {"enable_thinking": False}},
        ),
    )
]

### 🏗️ Initialize the Data Designer Config Builder

- The Data Designer config defines the dataset schema and generation process.

- The config builder provides an intuitive interface for building this configuration.

- The list of model configs is provided to the builder at initialization.

In [4]:
config_builder = dd.DataDesignerConfigBuilder(model_configs=model_configs)

### 🧑‍🎨 Designing our data

- We will again create a product review dataset, but this time we will use structured outputs and Jinja expressions.

- Structured outputs let you specify the exact schema of the data you want to generate.

- Data Designer supports schemas specified using either json schema or Pydantic data models (recommended).

<br>

We'll define our structured outputs using [Pydantic](https://docs.pydantic.dev/latest/) data models

> 💡 **Why Pydantic?**
>
> - Pydantic models provide better IDE support and type validation.
>
> - They are more Pythonic than raw JSON schemas.
>
> - They integrate seamlessly with Data Designer's structured output system.

In [5]:
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, Field


# We define a Product schema so that the name, description, and price are generated
# in one go, with the types and constraints specified.
class Product(BaseModel):
    name: str = Field(description="The name of the product")
    description: str = Field(description="A description of the product")
    price: Decimal = Field(description="The price of the product", ge=10, le=1000, decimal_places=2)


class ProductReview(BaseModel):
    rating: int = Field(description="The rating of the product", ge=1, le=5)
    customer_mood: Literal["irritated", "mad", "happy", "neutral", "excited"] = Field(
        description="The mood of the customer"
    )
    review: str = Field(description="A review of the product")

Next, let's design our product review dataset using a few more tricks compared to the previous notebook.

In [6]:
# Since we often only want a few attributes from Person objects, we can
# set drop=True in the column config to drop the column from the final dataset.
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="customer",
        sampler_type=dd.SamplerType.PERSON_FROM_FAKER,
        params=dd.PersonFromFakerSamplerParams(),
        drop=True,
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="product_category",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(
            values=[
                "Electronics",
                "Clothing",
                "Home & Kitchen",
                "Books",
                "Home Office",
            ],
        ),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="product_subcategory",
        sampler_type=dd.SamplerType.SUBCATEGORY,
        params=dd.SubcategorySamplerParams(
            category="product_category",
            values={
                "Electronics": [
                    "Smartphones",
                    "Laptops",
                    "Headphones",
                    "Cameras",
                    "Accessories",
                ],
                "Clothing": [
                    "Men's Clothing",
                    "Women's Clothing",
                    "Winter Coats",
                    "Activewear",
                    "Accessories",
                ],
                "Home & Kitchen": [
                    "Appliances",
                    "Cookware",
                    "Furniture",
                    "Decor",
                    "Organization",
                ],
                "Books": [
                    "Fiction",
                    "Non-Fiction",
                    "Self-Help",
                    "Textbooks",
                    "Classics",
                ],
                "Home Office": [
                    "Desks",
                    "Chairs",
                    "Storage",
                    "Office Supplies",
                    "Lighting",
                ],
            },
        ),
    )
)

config_builder.add_column(
    dd.SamplerColumnConfig(
        name="target_age_range",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(values=["18-25", "25-35", "35-50", "50-65", "65+"]),
    )
)

# Sampler columns support conditional params, which are used if the condition is met.
# In this example, we set the review style to rambling if the target age range is 18-25.
# Note conditional parameters are only supported for Sampler column types.
config_builder.add_column(
    dd.SamplerColumnConfig(
        name="review_style",
        sampler_type=dd.SamplerType.CATEGORY,
        params=dd.CategorySamplerParams(
            values=["rambling", "brief", "detailed", "structured with bullet points"],
            weights=[1, 2, 2, 1],
        ),
        conditional_params={
            "target_age_range == '18-25'": dd.CategorySamplerParams(values=["rambling"]),
        },
    )
)

# Optionally validate that the columns are configured correctly.
data_designer.validate(config_builder)

[12:06:02] [INFO] ✅ Validation passed

Next, we will use more advanced Jinja expressions to create new columns.

Jinja expressions let you:

- Access nested attributes: `{{ customer.first_name }}`

- Combine values: `{{ customer.first_name }} {{ customer.last_name }}`

- Use conditional logic: `{% if condition %}...{% endif %}`

In [7]:
# We can create new columns using Jinja expressions that reference
# existing columns, including attributes of nested objects.
config_builder.add_column(
    dd.ExpressionColumnConfig(name="customer_name", expr="{{ customer.first_name }} {{ customer.last_name }}")
)

config_builder.add_column(dd.ExpressionColumnConfig(name="customer_age", expr="{{ customer.age }}"))

config_builder.add_column(
    dd.LLMStructuredColumnConfig(
        name="product",
        prompt=(
            "Create a product in the '{{ product_category }}' category, focusing on products  "
            "related to '{{ product_subcategory }}'. The target age range of the ideal customer is "
            "{{ target_age_range }} years old. The product should be priced between $10 and $1000."
        ),
        output_format=Product,
        model_alias=MODEL_ALIAS,
    )
)

# We can even use if/else logic in our Jinja expressions to create more complex prompt patterns.
config_builder.add_column(
    dd.LLMStructuredColumnConfig(
        name="customer_review",
        prompt=(
            "Your task is to write a review for the following product:\n\n"
            "Product Name: {{ product.name }}\n"
            "Product Description: {{ product.description }}\n"
            "Price: {{ product.price }}\n\n"
            "Imagine your name is {{ customer_name }} and you are from {{ customer.city }}, {{ customer.state }}. "
            "Write the review in a style that is '{{ review_style }}'."
            "{% if target_age_range == '18-25' %}"
            "Make sure the review is more informal and conversational.\n"
            "{% else %}"
            "Make sure the review is more formal and structured.\n"
            "{% endif %}"
            "The review field should contain only the review, no other text."
        ),
        output_format=ProductReview,
        model_alias=MODEL_ALIAS,
    )
)

data_designer.validate(config_builder)

[12:06:02] [INFO] ✅ Validation passed

### 🔁 Iteration is key – preview the dataset!

1. Use the `preview` method to generate a sample of records quickly.

2. Inspect the results for quality and format issues.

3. Adjust column configurations, prompts, or parameters as needed.

4. Re-run the preview until satisfied.

In [8]:
preview = data_designer.preview(config_builder, num_records=2)

[12:06:02] [INFO] 👀 Preview generation in progress

[12:06:02] [INFO] ✅ Validation passed

[12:06:02] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[12:06:02] [INFO] 🩺 Running health checks for models...

[12:06:02] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...

[12:06:02] [INFO]   |-- ✅ Passed!

[12:06:02] [INFO] 🎲 Preparing samplers to generate 2 records across 5 columns

[12:06:03] [INFO] 🧩 Generating column `customer_name` from expression

[12:06:03] [INFO] 🧩 Generating column `customer_age` from expression

[12:06:03] [INFO] 🗂️ llm-structured model config for column 'product'

[12:06:03] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[12:06:03] [INFO]   |-- model alias: 'nemotron-nano-v3'

[12:06:03] [INFO]   |-- model provider: 'nvidia'

[12:06:03] [INFO]   |-- inference parameters:

[12:06:03] [INFO]   |  |-- generation_type=chat-completion

[12:06:03] [INFO]   |  |-- max_parallel_requests=4

[12:06:03] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[12:06:03] [INFO]   |  |-- temperature=1.00

[12:06:03] [INFO]   |  |-- top_p=1.00

[12:06:03] [INFO]   |  |-- max_tokens=2048

[12:06:03] [INFO] ⚡️ Processing llm-structured column 'product' with 4 concurrent workers

[12:06:03] [INFO] ⏱️ llm-structured column 'product' will report progress after each record

[12:06:03] [INFO]   |-- 🌗 llm-structured column 'product' progress: 1/2 (50%) complete, 1 ok, 0 failed, 1.37 rec/s, eta 0.7s

[12:06:07] [INFO]   |-- 🌕 llm-structured column 'product' progress: 2/2 (100%) complete, 2 ok, 0 failed, 0.50 rec/s, eta 0.0s

[12:06:07] [INFO] 🗂️ llm-structured model config for column 'customer_review'

[12:06:07] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[12:06:07] [INFO]   |-- model alias: 'nemotron-nano-v3'

[12:06:07] [INFO]   |-- model provider: 'nvidia'

[12:06:07] [INFO]   |-- inference parameters:

[12:06:07] [INFO]   |  |-- generation_type=chat-completion

[12:06:07] [INFO]   |  |-- max_parallel_requests=4

[12:06:07] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[12:06:07] [INFO]   |  |-- temperature=1.00

[12:06:07] [INFO]   |  |-- top_p=1.00

[12:06:07] [INFO]   |  |-- max_tokens=2048

[12:06:07] [INFO] ⚡️ Processing llm-structured column 'customer_review' with 4 concurrent workers

[12:06:07] [INFO] ⏱️ llm-structured column 'customer_review' will report progress after each record

[12:06:07] [INFO]   |-- 😐 llm-structured column 'customer_review' progress: 1/2 (50%) complete, 1 ok, 0 failed, 1.19 rec/s, eta 0.8s

[12:06:09] [INFO]   |-- 🤩 llm-structured column 'customer_review' progress: 2/2 (100%) complete, 2 ok, 0 failed, 1.05 rec/s, eta 0.0s

[12:06:09] [INFO] 📊 Model usage summary:

[12:06:09] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[12:06:09] [INFO]   |-- tokens: input=1319, output=686, total=2005, tps=325

[12:06:09] [INFO]   |-- requests: success=4, failed=0, total=4, rpm=38

[12:06:09] [INFO] 🙈 Dropping columns: ['customer']

[12:06:09] [INFO] 📐 Measuring dataset column statistics:

[12:06:09] [INFO]   |-- 🎲 column: 'product_category'

[12:06:09] [INFO]   |-- 🎲 column: 'product_subcategory'

[12:06:09] [INFO]   |-- 🎲 column: 'target_age_range'

[12:06:09] [INFO]   |-- 🎲 column: 'review_style'

[12:06:09] [INFO]   |-- 🧩 column: 'customer_name'

[12:06:09] [INFO]   |-- 🧩 column: 'customer_age'

[12:06:09] [INFO]   |-- 🗂️ column: 'product'

[12:06:09] [INFO]   |-- 🗂️ column: 'customer_review'

[12:06:09] [INFO] 🎆 Preview complete!

In [9]:
# Run this cell multiple times to cycle through the 2 preview records.
preview.display_sample_record()

                                              Generated Columns
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                ┃ Value                                                                                ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category    │ Electronics                                                                          │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ product_subcategory │ Accessories                                                                          │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ target_age_range    │ 35-50                                                                                │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ review_style        │ brief                                                                                │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ product             │ {                                                                                    │
│                     │     'name': 'Premium Bamboo Cable Organizer Set',                                    │
│                     │     'description': 'A sleek, sustainable cable management solution made from         │
│                     │ high-quality bamboo, perfect for organizing charging cables, power cords, and USB    │
│                     │ accessories on your home office desk or entertainment center. Includes three         │
│                     │ adjustable slots and a discreet magnetic closure, designed for professionals aged    │
│                     │ 35-50 who appreciate minimalist design and eco-friendly products.',                  │
│                     │     'price': 25.99                                                                   │
│                     │ }                                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer_review     │ {                                                                                    │
│                     │     'rating': 5,                                                                     │
│                     │     'customer_mood': 'happy',                                                        │
│                     │     'review': 'Robert Smith from Campbellmouth, Connecticut, presents a meticulously │
│                     │ crafted review of the Premium Bamboo Cable Organizer Set. The product delivers       │
│                     │ robust cable management with a minimalist bamboo aesthetic, aligning perfectly with  │
│                     │ the preferences of mid‑career professionals who prioritize sustainability.           │
│                     │ Adjustable slots accommodate diverse cord thicknesses, while the magnetic closure    │
│                     │ offers a refined, secure seal. The eco‑friendly material appeals to environmentally  │
│                     │ conscious users, and the competitive price point of $25.99 ensures value for         │
│                     │ budget‑aware consumers. Overall, the organizer exemplifies professional design and   │
│                     │ practical functionality, earning high satisfaction.'                                 │
│                     │ }                                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer_name       │ Robert Smith                                                                         │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────┤
│ customer_age        │ 47                                                                                   │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────┘

In [10]:
# The preview dataset is available as a pandas DataFrame.
preview.dataset

,product_category,product_subcategory,target_age_range,review_style,customer_name,customer_age,product,customer_review
0,Electronics,Accessories,35-50,brief,Robert Smith,47,"{'name': 'Premium Bamboo Cable Organizer Set',...","{'rating': 5, 'customer_mood': 'happy', 'revie..."
1,Electronics,Headphones,18-25,rambling,Christine Gonzales,25,"{'name': 'SolarSync Lite', 'description': 'A w...","{'rating': 5, 'customer_mood': 'happy', 'revie..."

### 📊 Analyze the generated data

- Data Designer automatically generates a basic statistical analysis of the generated data.

- This analysis is available via the `analysis` property of generation result objects.

In [11]:
# Print the analysis as a table.
preview.analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2                               │ 8                               │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                      ┃        data type ┃               number unique values ┃         sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category                 │           string │                          1 (50.0%) │             category │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ product_subcategory              │           string │                         2 (100.0%) │          subcategory │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ target_age_range                 │           string │                         2 (100.0%) │             category │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ review_style                     │           string │                         2 (100.0%) │             category │
└──────────────────────────────────┴──────────────────┴────────────────────────────────────┴──────────────────────┘


                                             🗂️ LLM-Structured Columns
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                       ┃               ┃                            ┃     prompt tokens ┃      completion tokens ┃
┃ column name           ┃     data type ┃       number unique values ┃        per record ┃             per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ product               │          dict │                 2 (100.0%) │     265.0 +/- 0.0 │           85.5 +/- 3.5 │
├───────────────────────┼───────────────┼────────────────────────────┼───────────────────┼────────────────────────┤
│ customer_review       │          dict │                 2 (100.0%) │     340.0 +/- 4.0 │        217.5 +/- 122.3 │
└───────────────────────┴───────────────┴────────────────────────────┴───────────────────┴────────────────────────┘


                                               🧩 Expression Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                       ┃                data type ┃                             number unique values ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ customer_name                     │                   string │                                       2 (100.0%) │
├───────────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────────┤
│ customer_age                      │                   string │                                       2 (100.0%) │
└───────────────────────────────────┴──────────────────────────┴──────────────────────────────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

### 🆙 Scale up!

- Happy with your preview data?

- Use the `create` method to submit larger Data Designer generation jobs.

In [12]:
results = data_designer.create(config_builder, num_records=10, dataset_name="tutorial-2")

[12:06:09] [INFO] 🎨 Creating Data Designer dataset

[12:06:09] [INFO] ✅ Validation passed

[12:06:09] [INFO] ⛓️ Sorting column configs into a Directed Acyclic Graph

[12:06:09] [INFO] 🩺 Running health checks for models...

[12:06:09] [INFO]   |-- 👀 Checking 'nvidia/nemotron-3-nano-30b-a3b' in provider named 'nvidia' for model alias 'nemotron-nano-v3'...

[12:06:10] [INFO]   |-- ✅ Passed!

[12:06:10] [INFO] ⏳ Processing batch 1 of 1

[12:06:10] [INFO] 🎲 Preparing samplers to generate 10 records across 5 columns

[12:06:10] [INFO] 🧩 Generating column `customer_name` from expression

[12:06:10] [INFO] 🧩 Generating column `customer_age` from expression

[12:06:10] [INFO] 🗂️ llm-structured model config for column 'product'

[12:06:10] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[12:06:10] [INFO]   |-- model alias: 'nemotron-nano-v3'

[12:06:10] [INFO]   |-- model provider: 'nvidia'

[12:06:10] [INFO]   |-- inference parameters:

[12:06:10] [INFO]   |  |-- generation_type=chat-completion

[12:06:10] [INFO]   |  |-- max_parallel_requests=4

[12:06:10] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[12:06:10] [INFO]   |  |-- temperature=1.00

[12:06:10] [INFO]   |  |-- top_p=1.00

[12:06:10] [INFO]   |  |-- max_tokens=2048

[12:06:10] [INFO] ⚡️ Processing llm-structured column 'product' with 4 concurrent workers

[12:06:10] [INFO] ⏱️ llm-structured column 'product' will report progress after each record

[12:06:11] [INFO]   |-- 😴 llm-structured column 'product' progress: 1/10 (10%) complete, 1 ok, 0 failed, 1.78 rec/s, eta 5.1s

[12:06:11] [INFO]   |-- 😴 llm-structured column 'product' progress: 2/10 (20%) complete, 2 ok, 0 failed, 3.45 rec/s, eta 2.3s

[12:06:11] [INFO]   |-- 🥱 llm-structured column 'product' progress: 3/10 (30%) complete, 3 ok, 0 failed, 4.59 rec/s, eta 1.5s

[12:06:11] [INFO]   |-- 🥱 llm-structured column 'product' progress: 4/10 (40%) complete, 4 ok, 0 failed, 4.84 rec/s, eta 1.2s

[12:06:11] [INFO]   |-- 😐 llm-structured column 'product' progress: 5/10 (50%) complete, 5 ok, 0 failed, 4.38 rec/s, eta 1.1s

[12:06:11] [INFO]   |-- 😐 llm-structured column 'product' progress: 6/10 (60%) complete, 6 ok, 0 failed, 4.62 rec/s, eta 0.9s

[12:06:12] [INFO]   |-- 😐 llm-structured column 'product' progress: 7/10 (70%) complete, 7 ok, 0 failed, 5.24 rec/s, eta 0.6s

[12:06:12] [INFO]   |-- 😊 llm-structured column 'product' progress: 8/10 (80%) complete, 8 ok, 0 failed, 5.31 rec/s, eta 0.4s

[12:06:12] [INFO]   |-- 😊 llm-structured column 'product' progress: 9/10 (90%) complete, 9 ok, 0 failed, 5.38 rec/s, eta 0.2s

[12:06:12] [INFO]   |-- 🤩 llm-structured column 'product' progress: 10/10 (100%) complete, 10 ok, 0 failed, 4.95 rec/s, eta 0.0s

[12:06:12] [INFO] 🗂️ llm-structured model config for column 'customer_review'

[12:06:12] [INFO]   |-- model: 'nvidia/nemotron-3-nano-30b-a3b'

[12:06:12] [INFO]   |-- model alias: 'nemotron-nano-v3'

[12:06:12] [INFO]   |-- model provider: 'nvidia'

[12:06:12] [INFO]   |-- inference parameters:

[12:06:12] [INFO]   |  |-- generation_type=chat-completion

[12:06:12] [INFO]   |  |-- max_parallel_requests=4

[12:06:12] [INFO]   |  |-- extra_body={'chat_template_kwargs': {'enable_thinking': False}}

[12:06:12] [INFO]   |  |-- temperature=1.00

[12:06:12] [INFO]   |  |-- top_p=1.00

[12:06:12] [INFO]   |  |-- max_tokens=2048

[12:06:12] [INFO] ⚡️ Processing llm-structured column 'customer_review' with 4 concurrent workers

[12:06:12] [INFO] ⏱️ llm-structured column 'customer_review' will report progress after each record

[12:06:13] [INFO]   |-- 🐱 llm-structured column 'customer_review' progress: 1/10 (10%) complete, 1 ok, 0 failed, 1.68 rec/s, eta 5.4s

[12:06:13] [INFO]   |-- 🐱 llm-structured column 'customer_review' progress: 2/10 (20%) complete, 2 ok, 0 failed, 2.67 rec/s, eta 3.0s

[12:06:13] [INFO]   |-- 😺 llm-structured column 'customer_review' progress: 3/10 (30%) complete, 3 ok, 0 failed, 2.65 rec/s, eta 2.6s

[12:06:13] [INFO]   |-- 😺 llm-structured column 'customer_review' progress: 4/10 (40%) complete, 4 ok, 0 failed, 3.18 rec/s, eta 1.9s

[12:06:14] [INFO]   |-- 😸 llm-structured column 'customer_review' progress: 5/10 (50%) complete, 5 ok, 0 failed, 3.84 rec/s, eta 1.3s

[12:06:14] [INFO]   |-- 😸 llm-structured column 'customer_review' progress: 6/10 (60%) complete, 6 ok, 0 failed, 3.72 rec/s, eta 1.1s

[12:06:14] [INFO]   |-- 😸 llm-structured column 'customer_review' progress: 7/10 (70%) complete, 7 ok, 0 failed, 3.70 rec/s, eta 0.8s

[12:06:14] [INFO]   |-- 😼 llm-structured column 'customer_review' progress: 8/10 (80%) complete, 8 ok, 0 failed, 4.18 rec/s, eta 0.5s

[12:06:15] [INFO]   |-- 😼 llm-structured column 'customer_review' progress: 9/10 (90%) complete, 9 ok, 0 failed, 3.26 rec/s, eta 0.3s

[12:06:15] [INFO]   |-- 🦁 llm-structured column 'customer_review' progress: 10/10 (100%) complete, 10 ok, 0 failed, 3.24 rec/s, eta 0.0s

[12:06:15] [INFO] 🙈 Dropping columns: ['customer']

[12:06:15] [INFO] 📊 Model usage summary:

[12:06:15] [INFO]   |-- model: nvidia/nemotron-3-nano-30b-a3b

[12:06:15] [INFO]   |-- tokens: input=6680, output=3114, total=9794, tps=1816

[12:06:15] [INFO]   |-- requests: success=20, failed=0, total=20, rpm=222

[12:06:16] [INFO] 📐 Measuring dataset column statistics:

[12:06:16] [INFO]   |-- 🎲 column: 'product_category'

[12:06:16] [INFO]   |-- 🎲 column: 'product_subcategory'

[12:06:16] [INFO]   |-- 🎲 column: 'target_age_range'

[12:06:16] [INFO]   |-- 🎲 column: 'review_style'

[12:06:16] [INFO]   |-- 🧩 column: 'customer_name'

[12:06:16] [INFO]   |-- 🧩 column: 'customer_age'

[12:06:16] [INFO]   |-- 🗂️ column: 'product'

[12:06:16] [INFO]   |-- 🗂️ column: 'customer_review'

In [13]:
# Load the generated dataset as a pandas DataFrame.
dataset = results.load_dataset()

dataset.head()

,product_category,product_subcategory,target_age_range,review_style,customer_name,customer_age,product,customer_review
0,Home Office,Storage,18-25,rambling,David Morton,78,"{'description': 'A sleek, wall-mountable stora...","{'customer_mood': 'excited', 'rating': 4, 'rev..."
1,Clothing,Women's Clothing,35-50,brief,Christian Nelson,97,"{'description': 'A tailored, soft alpaca wool ...","{'customer_mood': 'happy', 'rating': 5, 'revie..."
2,Books,Non-Fiction,18-25,rambling,Kristi Tucker,103,{'description': 'A compelling collection of ca...,"{'customer_mood': 'excited', 'rating': 4, 'rev..."
3,Electronics,Smartphones,50-65,structured with bullet points,Christopher Stanley,71,"{'description': 'A user‑friendly, large‑displa...","{'customer_mood': 'excited', 'rating': 4, 'rev..."
4,Books,Non-Fiction,65+,structured with bullet points,James Schmidt,30,{'description': 'A curated collection of ten n...,"{'customer_mood': 'happy', 'rating': 4, 'revie..."

In [14]:
# Load the analysis results into memory.
analysis = results.load_analysis()

analysis.to_report()

──────────────────────────────────────── 🎨 Data Designer Dataset Profile ─────────────────────────────────────────


                                                 Dataset Overview
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ number of records               ┃ number of columns               ┃ percent complete records                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 10                              │ 8                               │ 100.0%                                      │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────────────────┘


                                                🎲 Sampler Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                      ┃        data type ┃               number unique values ┃         sampler type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ product_category                 │           string │                          5 (50.0%) │             category │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ product_subcategory              │           string │                          9 (90.0%) │          subcategory │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ target_age_range                 │           string │                          5 (50.0%) │             category │
├──────────────────────────────────┼──────────────────┼────────────────────────────────────┼──────────────────────┤
│ review_style                     │           string │                          3 (30.0%) │             category │
└──────────────────────────────────┴──────────────────┴────────────────────────────────────┴──────────────────────┘


                                             🗂️ LLM-Structured Columns
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃                      ┃               ┃                            ┃       prompt tokens ┃     completion tokens ┃
┃ column name          ┃     data type ┃       number unique values ┃          per record ┃            per record ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ product              │          dict │                10 (100.0%) │       265.0 +/- 1.0 │         83.5 +/- 22.6 │
├──────────────────────┼───────────────┼────────────────────────────┼─────────────────────┼───────────────────────┤
│ customer_review      │          dict │                10 (100.0%) │      339.5 +/- 22.0 │       124.5 +/- 121.8 │
└──────────────────────┴───────────────┴────────────────────────────┴─────────────────────┴───────────────────────┘


                                               🧩 Expression Columns
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ column name                       ┃                data type ┃                             number unique values ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ customer_name                     │                   string │                                      10 (100.0%) │
├───────────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────────┤
│ customer_age                      │                   string │                                        9 (90.0%) │
└───────────────────────────────────┴──────────────────────────┴──────────────────────────────────────────────────┘


╭────────────────────────────────────────────────── Table Notes ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  1. All token statistics are based on a sample of max(1000, len(dataset)) records.                              │
│  2. Tokens are calculated using tiktoken's cl100k_base tokenizer.                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────

## ⏭️ Next Steps

Check out the following notebook to learn more about:

- [Seeding synthetic data generation with an external dataset](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/3-seeding-with-a-dataset/)

- [Providing images as context](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/4-providing-images-as-context/)

- [Generating images](https://nvidia-nemo.github.io/DataDesigner/latest/notebooks/5-generating-images/)